import type {
  User,
  Prospect,
  Property,
  Conversation,
  Campaign,
  Appointment,
  Integration,
  LiveConversation,
  CampaignRun,
  RoutingRule,
  HandoffPackage,
  Channel,
} from "./types"

export function getChannelIcon(channel: Channel): string {
  const icons: Record<Channel, string> = {
    phone: "Phone",
    whatsapp: "MessageCircle",
    sms: "MessageSquare",
    email: "Mail",
  }
  return icons[channel]
}

export function getChannelColor(channel: Channel): string {
  const colors: Record<Channel, string> = {
    phone: "bg-blue-500/20 text-blue-500 border-blue-500/30",
    whatsapp: "bg-emerald-500/20 text-emerald-500 border-emerald-500/30",
    sms: "bg-violet-500/20 text-violet-500 border-violet-500/30",
    email: "bg-amber-500/20 text-amber-500 border-amber-500/30",
  }
  return colors[channel]
}

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ahmed Al-Mansour",
    email: "ahmed@fph.sa",
    role: "admin",
    status: "active",
    lastActive: "2 minutes ago",
  },
  {
    id: "2",
    name: "Sarah Al-Rashid",
    email: "sarah@fph.sa",
    role: "sales_manager",
    status: "active",
    lastActive: "15 minutes ago",
  },
  {
    id: "3",
    name: "Mohammed Al-Farsi",
    email: "mohammed@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "1 hour ago",
  },
  {
    id: "4",
    name: "Layla Hassan",
    email: "layla@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "30 minutes ago",
  },
  {
    id: "5",
    name: "Omar Al-Saud",
    email: "omar@fph.sa",
    role: "qa_supervisor",
    status: "active",
    lastActive: "2 hours ago",
  },
  {
    id: "6",
    name: "Noor Al-Khaled",
    email: "noor@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "45 minutes ago",
  },
  {
    id: "7",
    name: "Yusuf Al-Najjar",
    email: "yusuf@fph.sa",
    role: "compliance_officer",
    status: "active",
    lastActive: "3 hours ago",
  },
  {
    id: "8",
    name: "Amira Khalil",
    email: "amira@fph.sa",
    role: "sales_manager",
    status: "active",
    lastActive: "1 hour ago",
  },
  {
    id: "9",
    name: "Faisal Al-Dossary",
    email: "faisal@fph.sa",
    role: "sales_rep",
    status: "inactive",
    lastActive: "2 days ago",
  },
  {
    id: "10",
    name: "Hana Al-Qasim",
    email: "hana@fph.sa",
    role: "operations",
    status: "active",
    lastActive: "20 minutes ago",
  },
  {
    id: "11",
    name: "Ibrahim Al-Tamimi",
    email: "ibrahim@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "10 minutes ago",
  },
  {
    id: "12",
    name: "Maha Al-Shehri",
    email: "maha@fph.sa",
    role: "qa_supervisor",
    status: "active",
    lastActive: "5 hours ago",
  },
]

export const mockProspects: Prospect[] = [
  {
    id: "1",
    name: "Khalid Abdullah",
    email: "khalid@example.com",
    phone: "+966 50 123 4567",
    whatsapp: "+966 50 123 4567",
    budget: "3-5M SAR",
    city: "Riyadh",
    timeline: "3-6 months",
    status: "qualified",
    assignedTo: "3",
    lastContact: "2024-01-15",
    preferredChannel: "whatsapp",
  },
  {
    id: "2",
    name: "Fatima Al-Zahrani",
    email: "fatima@example.com",
    phone: "+966 55 234 5678",
    whatsapp: "+966 55 234 5678",
    budget: "5-8M SAR",
    city: "Jeddah",
    timeline: "1-3 months",
    status: "appointment_set",
    assignedTo: "3",
    lastContact: "2024-01-14",
    preferredChannel: "phone",
  },
  {
    id: "3",
    name: "Sultan Al-Harbi",
    email: "sultan@example.com",
    phone: "+966 50 345 6789",
    whatsapp: "+966 50 345 6789",
    budget: "8-12M SAR",
    city: "Riyadh",
    timeline: "6-12 months",
    status: "contacted",
    assignedTo: "4",
    lastContact: "2024-01-13",
    preferredChannel: "email",
  },
  {
    id: "4",
    name: "Mariam Al-Ghamdi",
    email: "mariam@example.com",
    phone: "+966 55 456 7890",
    whatsapp: "+966 55 456 7890",
    budget: "4-6M SAR",
    city: "Dammam",
    timeline: "1-3 months",
    status: "qualified",
    assignedTo: "6",
    lastContact: "2024-01-15",
    preferredChannel: "whatsapp",
  },
  {
    id: "5",
    name: "Abdullah Al-Mutairi",
    email: "abdullah.m@example.com",
    phone: "+966 50 567 8901",
    whatsapp: "+966 50 567 8901",
    budget: "10-15M SAR",
    city: "Riyadh",
    timeline: "3-6 months",
    status: "appointment_set",
    assignedTo: "3",
    lastContact: "2024-01-14",
    preferredChannel: "phone",
  },
  {
    id: "6",
    name: "Aisha Al-Harthi",
    email: "aisha@example.com",
    phone: "+966 55 678 9012",
    budget: "2-4M SAR",
    city: "Jeddah",
    timeline: "6-12 months",
    status: "new",
    assignedTo: "4",
    lastContact: "2024-01-12",
    preferredChannel: "sms",
  },
  {
    id: "7",
    name: "Nasser Al-Otaibi",
    email: "nasser@example.com",
    phone: "+966 50 789 0123",
    whatsapp: "+966 50 789 0123",
    budget: "6-9M SAR",
    city: "Riyadh",
    timeline: "1-3 months",
    status: "qualified",
    assignedTo: "11",
    lastContact: "2024-01-15",
    preferredChannel: "whatsapp",
  },
  {
    id: "8",
    name: "Sara Al-Qahtani",
    email: "sara.q@example.com",
    phone: "+966 55 890 1234",
    whatsapp: "+966 55 890 1234",
    budget: "15-20M SAR",
    city: "Riyadh",
    timeline: "1-3 months",
    status: "qualified",
    assignedTo: "3",
    lastContact: "2024-01-15",
    preferredChannel: "phone",
  },
  {
    id: "9",
    name: "Turki Al-Shamrani",
    email: "turki@example.com",
    phone: "+966 50 901 2345",
    budget: "5-7M SAR",
    city: "Jeddah",
    timeline: "3-6 months",
    status: "contacted",
    assignedTo: "6",
    lastContact: "2024-01-14",
    preferredChannel: "email",
  },
  {
    id: "10",
    name: "Noura Al-Dosari",
    email: "noura@example.com",
    phone: "+966 55 012 3456",
    whatsapp: "+966 55 012 3456",
    budget: "8-10M SAR",
    city: "Dammam",
    timeline: "6-12 months",
    status: "new",
    assignedTo: "4",
    lastContact: "2024-01-13",
    preferredChannel: "whatsapp",
  },
]

export const mockProperties: Property[] = [
  {
    id: "1",
    name: "Azure Heights Villa",
    city: "Riyadh",
    priceRange: "4.5M - 5.2M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Luxury villa with smart home integration and private pool",
    features: ["Private Pool", "Smart Home", "Garden", "24/7 Security"],
    imageUrl: "/luxury-modern-villa-with-pool-riyadh.jpg",
  },
  {
    id: "2",
    name: "Pearl Tower Penthouse",
    city: "Jeddah",
    priceRange: "6.8M - 7.5M SAR",
    bedrooms: 3,
    type: "penthouse",
    status: "available",
    description: "Stunning sea view penthouse with rooftop terrace",
    features: ["Sea View", "Rooftop Terrace", "Private Elevator", "Concierge"],
    imageUrl: "/luxury-penthouse-sea-view-jeddah.jpg",
  },
  {
    id: "3",
    name: "Golden Oasis Residence",
    city: "Riyadh",
    priceRange: "3.2M - 3.8M SAR",
    bedrooms: 3,
    type: "villa",
    status: "available",
    description: "Modern villa in gated community with full amenities",
    features: ["Gated Community", "Gym Access", "Children Play Area", "Covered Parking"],
    imageUrl: "/modern-villa-gated-community-riyadh.jpg",
  },
  {
    id: "4",
    name: "Coral Bay Apartments",
    city: "Dammam",
    priceRange: "1.8M - 2.4M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Waterfront living with stunning bay views",
    features: ["Waterfront", "Balcony", "Parking", "Pool Access"],
    imageUrl: "/waterfront-apartment-dammam-bay-view.jpg",
  },
  {
    id: "5",
    name: "Royal Palm Estate",
    city: "Riyadh",
    priceRange: "12M - 15M SAR",
    bedrooms: 6,
    type: "villa",
    status: "available",
    description: "Ultra-luxury estate with private grounds and guest house",
    features: ["Private Grounds", "Guest House", "Home Theater", "Wine Cellar"],
    imageUrl: "/ultra-luxury-mansion-estate-riyadh.jpg",
  },
  {
    id: "6",
    name: "Sapphire Towers",
    city: "Jeddah",
    priceRange: "2.1M - 2.6M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Contemporary high-rise living in the heart of Jeddah",
    features: ["City View", "Gym", "Swimming Pool", "24/7 Concierge"],
    imageUrl: "/modern-high-rise-apartment-jeddah-city.jpg",
  },
  {
    id: "7",
    name: "Desert Rose Villa",
    city: "Riyadh",
    priceRange: "5.8M - 6.5M SAR",
    bedrooms: 5,
    type: "villa",
    status: "reserved",
    description: "Elegant villa with traditional Arabian architecture",
    features: ["Majlis", "Indoor Garden", "Driver's Room", "Maid's Room"],
    imageUrl: "/arabian-traditional-villa-riyadh.jpg",
  },
  {
    id: "8",
    name: "Marina Vista Penthouse",
    city: "Dammam",
    priceRange: "4.2M - 4.8M SAR",
    bedrooms: 4,
    type: "penthouse",
    status: "available",
    description: "Exclusive penthouse overlooking the Arabian Gulf",
    features: ["Marina View", "Private Terrace", "Jacuzzi", "Smart Home"],
    imageUrl: "/marina-penthouse-arabian-gulf-view.jpg",
  },
  {
    id: "9",
    name: "Emerald Gardens Townhouse",
    city: "Riyadh",
    priceRange: "2.8M - 3.3M SAR",
    bedrooms: 3,
    type: "townhouse",
    status: "available",
    description: "Family-friendly townhouse with private garden",
    features: ["Private Garden", "Community Park", "School Nearby", "Shopping Center"],
    imageUrl: "/modern-townhouse-garden-riyadh.jpg",
  },
  {
    id: "10",
    name: "Crystal Palace Residence",
    city: "Jeddah",
    priceRange: "8.5M - 9.2M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Palatial villa with marble finishes and grand entrance",
    features: ["Marble Finishes", "Grand Entrance", "Fountain", "Multiple Lounges"],
    imageUrl: "/palatial-luxury-villa-marble-jeddah.jpg",
  },
  {
    id: "11",
    name: "Horizon Heights",
    city: "Riyadh",
    priceRange: "1.5M - 1.9M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Affordable modern living with great amenities",
    features: ["Gym", "Parking", "Central Location", "Maintenance Service"],
    imageUrl: "/affordable-modern-apartment-riyadh.jpg",
  },
  {
    id: "12",
    name: "Platinum Residence",
    city: "Dammam",
    priceRange: "3.5M - 4.1M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Contemporary villa in prime location",
    features: ["Modern Design", "Large Windows", "Open Kitchen", "Landscaped Garden"],
    imageUrl: "/contemporary-villa-modern-design-dammam.jpg",
  },
  {
    id: "13",
    name: "Silver Dunes Estate",
    city: "Riyadh",
    priceRange: "7.2M - 8.0M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Spacious villa with traditional and modern elements",
    features: ["Indoor Pool", "Home Office", "Entertainment Room", "Solar Panels"],
    imageUrl: "/spacious-villa-modern-traditional-riyadh.jpg",
  },
  {
    id: "14",
    name: "Amber Towers",
    city: "Jeddah",
    priceRange: "2.9M - 3.4M SAR",
    bedrooms: 3,
    type: "apartment",
    status: "sold",
    description: "Premium apartment with Red Sea views",
    features: ["Sea View", "High Floor", "Modern Kitchen", "Storage Room"],
    imageUrl: "/apartment-red-sea-view-jeddah.jpg",
  },
  {
    id: "15",
    name: "Oasis Springs Villa",
    city: "Riyadh",
    priceRange: "4.0M - 4.7M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Villa with natural spring water features",
    features: ["Water Features", "Landscaping", "BBQ Area", "Outdoor Kitchen"],
    imageUrl: "/villa-water-features-landscaping-riyadh.jpg",
  },
  {
    id: "16",
    name: "Diamond District Loft",
    city: "Dammam",
    priceRange: "2.2M - 2.7M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Modern loft-style apartment for professionals",
    features: ["Open Plan", "High Ceilings", "Designer Finishes", "Co-working Space"],
    imageUrl: "/modern-high-rise-apartment-jeddah-city.jpg",
  },
  {
    id: "17",
    name: "Royal Gardens Mansion",
    city: "Riyadh",
    priceRange: "18M - 22M SAR",
    bedrooms: 7,
    type: "villa",
    status: "available",
    description: "Magnificent mansion with botanical gardens",
    features: ["Botanical Gardens", "Tennis Court", "Staff Quarters", "Security Lodge"],
    imageUrl: "/ultra-luxury-mansion-estate-riyadh.jpg",
  },
  {
    id: "18",
    name: "Sunset Boulevard Penthouse",
    city: "Jeddah",
    priceRange: "5.5M - 6.2M SAR",
    bedrooms: 3,
    type: "penthouse",
    status: "reserved",
    description: "Stunning penthouse with panoramic sunset views",
    features: ["Panoramic Views", "Chef's Kitchen", "Wine Cellar", "Home Automation"],
    imageUrl: "/luxury-penthouse-sea-view-jeddah.jpg",
  },
  {
    id: "19",
    name: "Green Valley Townhouse",
    city: "Riyadh",
    priceRange: "2.5M - 2.9M SAR",
    bedrooms: 3,
    type: "townhouse",
    status: "available",
    description: "Eco-friendly townhouse in sustainable community",
    features: ["Solar Power", "Energy Efficient", "Green Spaces", "Bike Paths"],
    imageUrl: "/modern-townhouse-garden-riyadh.jpg",
  },
  {
    id: "20",
    name: "Coastal Breeze Apartment",
    city: "Dammam",
    priceRange: "1.6M - 2.0M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Beachfront living with ocean breeze",
    features: ["Beach Access", "Sea Breeze", "Balcony", "Furnished Option"],
    imageUrl: "/waterfront-apartment-dammam-bay-view.jpg",
  },
  {
    id: "21",
    name: "Paradise Hills Villa",
    city: "Jeddah",
    priceRange: "6.5M - 7.2M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Hillside villa with mountain and sea views",
    features: ["Mountain View", "Sea View", "Infinity Pool", "Outdoor Lounge"],
    imageUrl: "/luxury-modern-villa-with-pool-riyadh.jpg",
  },
  {
    id: "22",
    name: "Metropolitan Square",
    city: "Riyadh",
    priceRange: "2.7M - 3.2M SAR",
    bedrooms: 3,
    type: "apartment",
    status: "available",
    description: "Urban living in the business district",
    features: ["Business District", "Metro Access", "Retail Below", "Valet Parking"],
    imageUrl: "/affordable-modern-apartment-riyadh.jpg",
  },
  {
    id: "23",
    name: "Heritage Palace",
    city: "Riyadh",
    priceRange: "15M - 18M SAR",
    bedrooms: 6,
    type: "villa",
    status: "available",
    description: "Restored heritage palace with modern amenities",
    features: ["Heritage Architecture", "Courtyard", "Modern Interior", "Art Gallery"],
    imageUrl: "/arabian-traditional-villa-riyadh.jpg",
  },
  {
    id: "24",
    name: "Azure Bay Residences",
    city: "Dammam",
    priceRange: "3.8M - 4.4M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Waterfront villa with private beach access",
    features: ["Private Beach", "Boat Dock", "Beach House", "Outdoor Shower"],
    imageUrl: "/waterfront-apartment-dammam-bay-view.jpg",
  },
  {
    id: "25",
    name: "Skyline Tower Penthouse",
    city: "Riyadh",
    priceRange: "9.5M - 11M SAR",
    bedrooms: 4,
    type: "penthouse",
    status: "available",
    description: "Ultra-modern penthouse at the top of iconic tower",
    features: ["360 Views", "Sky Lounge", "Private Pool", "Helipad Access"],
    imageUrl: "/marina-penthouse-arabian-gulf-view.jpg",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "1",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    campaignId: "1",
    timestamp: "2024-01-15T10:30:00",
    duration: 420,
    channel: "phone",
    outcome: "qualified",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: false,
    qualificationScore: {
      intentScore: 85,
      budgetFitScore: 90,
      urgency: "high",
      propertyMatchConfidence: 88,
      riskFlags: [],
      overallScore: 87,
    },
  },
  {
    id: "2",
    prospectId: "2",
    prospectName: "Fatima Al-Zahrani",
    campaignId: "1",
    timestamp: "2024-01-15T11:15:00",
    duration: 0,
    channel: "whatsapp",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: true,
    messageCount: 24,
    qualificationScore: {
      intentScore: 92,
      budgetFitScore: 85,
      urgency: "high",
      propertyMatchConfidence: 90,
      riskFlags: ["Complex financing needs"],
      overallScore: 89,
    },
  },
  {
    id: "3",
    prospectId: "3",
    prospectName: "Sultan Al-Harbi",
    timestamp: "2024-01-15T09:00:00",
    duration: 180,
    channel: "phone",
    outcome: "connected",
    sentiment: "neutral",
    aiConfidence: "medium",
    handoffSuggested: false,
  },
  {
    id: "4",
    prospectId: "4",
    prospectName: "Mariam Al-Ghamdi",
    campaignId: "2",
    timestamp: "2024-01-15T14:30:00",
    duration: 0,
    channel: "sms",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "medium",
    messageCount: 8,
  },
  {
    id: "5",
    prospectId: "5",
    prospectName: "Abdullah Al-Mutairi",
    campaignId: "1",
    timestamp: "2024-01-15T15:00:00",
    duration: 540,
    channel: "phone",
    outcome: "qualified",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: true,
    qualificationScore: {
      intentScore: 95,
      budgetFitScore: 92,
      urgency: "high",
      propertyMatchConfidence: 94,
      riskFlags: [],
      overallScore: 94,
    },
  },
  {
    id: "6",
    prospectId: "6",
    prospectName: "Aisha Al-Harthi",
    timestamp: "2024-01-15T12:00:00",
    duration: 0,
    channel: "email",
    outcome: "opened",
    sentiment: "neutral",
    aiConfidence: "low",
  },
  {
    id: "7",
    prospectId: "7",
    prospectName: "Nasser Al-Otaibi",
    campaignId: "3",
    timestamp: "2024-01-15T16:30:00",
    duration: 0,
    channel: "whatsapp",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "high",
    messageCount: 18,
    handoffSuggested: false,
  },
  {
    id: "8",
    prospectId: "8",
    prospectName: "Sara Al-Qahtani",
    campaignId: "1",
    timestamp: "2024-01-14T10:00:00",
    duration: 380,
    channel: "phone",
    outcome: "qualified",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: true,
    qualificationScore: {
      intentScore: 88,
      budgetFitScore: 95,
      urgency: "medium",
      propertyMatchConfidence: 85,
      riskFlags: ["Decision maker unclear"],
      overallScore: 89,
    },
  },
  {
    id: "9",
    prospectId: "9",
    prospectName: "Turki Al-Shamrani",
    timestamp: "2024-01-14T14:30:00",
    duration: 0,
    channel: "email",
    outcome: "clicked",
    sentiment: "neutral",
    aiConfidence: "medium",
  },
  {
    id: "10",
    prospectId: "10",
    prospectName: "Noura Al-Dosari",
    campaignId: "2",
    timestamp: "2024-01-14T11:00:00",
    duration: 0,
    channel: "whatsapp",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "medium",
    messageCount: 12,
  },
]

// Keep mockCalls as alias for backward compatibility
export const mockCalls = mockConversations

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    name: "Riyadh Q1 Luxury Villas",
    segment: "High-Net-Worth, Riyadh",
    status: "active",
    channels: ["phone", "whatsapp", "email"],
    attempts: 2847,
    connectRate: 44,
    bookedAppointments: 127,
    createdBy: "2",
    createdAt: "2024-01-01",
    channelMetrics: {
      phone: { sent: 1200, connected: 528, rate: 44 },
      whatsapp: { sent: 1000, responded: 680, rate: 68 },
      email: { sent: 647, opened: 324, clicked: 89, rate: 14 },
    },
  },
  {
    id: "2",
    name: "Jeddah Waterfront Launch",
    segment: "Property Investors",
    status: "active",
    channels: ["whatsapp", "sms"],
    attempts: 1523,
    connectRate: 52,
    bookedAppointments: 89,
    createdBy: "2",
    createdAt: "2024-01-05",
    channelMetrics: {
      whatsapp: { sent: 1000, responded: 520, rate: 52 },
      sms: { sent: 523, responded: 183, rate: 35 },
    },
  },
  {
    id: "3",
    name: "Dammam First-Time Buyers",
    segment: "First-Time Buyers",
    status: "paused",
    channels: ["phone", "sms", "email"],
    attempts: 892,
    connectRate: 38,
    bookedAppointments: 34,
    createdBy: "8",
    createdAt: "2024-01-08",
    channelMetrics: {
      phone: { sent: 400, connected: 152, rate: 38 },
      sms: { sent: 300, responded: 87, rate: 29 },
      email: { sent: 192, opened: 96, clicked: 24, rate: 13 },
    },
  },
  {
    id: "4",
    name: "VIP Re-engagement",
    segment: "Previous Inquiries",
    status: "completed",
    channels: ["phone", "whatsapp"],
    attempts: 456,
    connectRate: 62,
    bookedAppointments: 78,
    createdBy: "2",
    createdAt: "2023-12-15",
    channelMetrics: {
      phone: { sent: 256, connected: 159, rate: 62 },
      whatsapp: { sent: 200, responded: 156, rate: 78 },
    },
  },
  {
    id: "5",
    name: "New Year Special Offers",
    segment: "All Segments",
    status: "draft",
    channels: ["email", "whatsapp", "sms"],
    attempts: 0,
    connectRate: 0,
    bookedAppointments: 0,
    createdBy: "8",
    createdAt: "2024-01-12",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    propertyId: "1",
    propertyName: "Azure Heights Villa",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-15T14:00:00",
    location: "Azure Heights Sales Center, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "2",
    prospectId: "2",
    prospectName: "Fatima Al-Zahrani",
    propertyId: "2",
    propertyName: "Pearl Tower Penthouse",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-16T10:00:00",
    location: "Pearl Tower Show Unit, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "3",
    prospectId: "5",
    prospectName: "Abdullah Al-Mutairi",
    propertyId: "5",
    propertyName: "Royal Palm Estate",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-18T16:00:00",
    location: "Royal Palm Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "4",
    prospectId: "8",
    prospectName: "Sara Al-Qahtani",
    propertyId: "5",
    propertyName: "Royal Palm Estate",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-17T11:00:00",
    location: "Royal Palm Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "5",
    prospectId: "4",
    prospectName: "Mariam Al-Ghamdi",
    propertyId: "4",
    propertyName: "Coral Bay Apartments",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2025-12-19T15:00:00",
    location: "Coral Bay Sales Office, Dammam",
    status: "scheduled",
    sourceChannel: "sms",
  },
  {
    id: "6",
    prospectId: "7",
    prospectName: "Nasser Al-Otaibi",
    propertyId: "3",
    propertyName: "Golden Oasis Residence",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2025-12-10T09:00:00",
    location: "Golden Oasis Community Center, Riyadh",
    status: "completed",
    notes: "Very interested, requested pricing details",
    sourceChannel: "whatsapp",
  },
  {
    id: "7",
    prospectId: "9",
    prospectName: "Omar Hassan",
    propertyId: "6",
    propertyName: "Sapphire Towers",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-20T13:00:00",
    location: "Sapphire Towers Sales Office, Jeddah",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "8",
    prospectId: "10",
    prospectName: "Aisha Al-Najjar",
    propertyId: "8",
    propertyName: "Marina Vista Penthouse",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2025-12-21T10:30:00",
    location: "Marina Vista Show Unit, Dammam",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "9",
    prospectId: "11",
    prospectName: "Yousef Al-Mansour",
    propertyId: "10",
    propertyName: "Crystal Palace Residence",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-22T14:30:00",
    location: "Crystal Palace, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "10",
    prospectId: "12",
    prospectName: "Huda Al-Salem",
    propertyId: "11",
    propertyName: "Horizon Heights",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2025-12-23T09:00:00",
    location: "Horizon Heights Sales Center, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "11",
    prospectId: "13",
    prospectName: "Tariq Al-Zahrani",
    propertyId: "13",
    propertyName: "Silver Dunes Estate",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-24T11:00:00",
    location: "Silver Dunes Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "12",
    prospectId: "14",
    prospectName: "Layla Al-Rashid",
    propertyId: "15",
    propertyName: "Oasis Springs Villa",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-26T15:00:00",
    location: "Oasis Springs, Riyadh",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "13",
    prospectId: "15",
    prospectName: "Hassan Al-Harbi",
    propertyId: "17",
    propertyName: "Royal Gardens Mansion",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-27T10:00:00",
    location: "Royal Gardens, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "14",
    prospectId: "16",
    prospectName: "Reem Al-Dosari",
    propertyId: "19",
    propertyName: "Green Valley Townhouse",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2025-12-28T13:30:00",
    location: "Green Valley Community, Riyadh",
    status: "scheduled",
    sourceChannel: "sms",
  },
  {
    id: "15",
    prospectId: "17",
    prospectName: "Fahad Al-Shammari",
    propertyId: "21",
    propertyName: "Paradise Hills Villa",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-29T16:00:00",
    location: "Paradise Hills, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "16",
    prospectId: "18",
    prospectName: "Mona Al-Harthi",
    propertyId: "22",
    propertyName: "Metropolitan Square",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2025-12-30T11:00:00",
    location: "Metropolitan Square, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "17",
    prospectId: "19",
    prospectName: "Saud Al-Ghamdi",
    propertyId: "24",
    propertyName: "Azure Bay Residences",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2026-01-02T10:00:00",
    location: "Azure Bay, Dammam",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "18",
    prospectId: "20",
    prospectName: "Nora Al-Mutairi",
    propertyId: "25",
    propertyName: "Skyline Tower Penthouse",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2026-01-03T14:00:00",
    location: "Skyline Tower, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "19",
    prospectId: "21",
    prospectName: "Ahmed Al-Jaber",
    propertyId: "7",
    propertyName: "Desert Rose Villa",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2026-01-04T09:30:00",
    location: "Desert Rose Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "20",
    prospectId: "22",
    prospectName: "Khaled Al-Subai",
    propertyId: "9",
    propertyName: "Emerald Gardens Townhouse",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2026-01-05T15:30:00",
    location: "Emerald Gardens, Riyadh",
    status: "scheduled",
    sourceChannel: "sms",
  },
  {
    id: "21",
    prospectId: "23",
    prospectName: "Salma Al-Qahtani",
    propertyId: "12",
    propertyName: "Platinum Residence",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2026-01-06T10:30:00",
    location: "Platinum Residence, Dammam",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "22",
    prospectId: "24",
    prospectName: "Majid Al-Faisal",
    propertyId: "16",
    propertyName: "Diamond District Loft",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2026-01-07T13:00:00",
    location: "Diamond District, Dammam",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "23",
    prospectId: "25",
    prospectName: "Lina Al-Harbi",
    propertyId: "18",
    propertyName: "Sunset Boulevard Penthouse",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2026-01-08T16:30:00",
    location: "Sunset Boulevard, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "24",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    propertyId: "20",
    propertyName: "Coastal Breeze Apartment",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2026-01-09T11:00:00",
    location: "Coastal Breeze, Dammam",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "25",
    prospectId: "3",
    prospectName: "Sarah Al-Amri",
    propertyId: "23",
    propertyName: "Heritage Palace",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2026-01-10T14:30:00",
    location: "Heritage Palace, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
]

export const mockIntegrations: Integration[] = [
  {
    id: "1",
    name: "Salesforce",
    type: "crm",
    status: "connected",
    lastSync: "2 minutes ago",
  },
  {
    id: "2",
    name: "Twilio Voice",
    type: "telephony",
    status: "connected",
    lastSync: "Real-time",
  },
  {
    id: "3",
    name: "WhatsApp Business API",
    type: "messaging",
    status: "connected",
    lastSync: "Real-time",
  },
  {
    id: "4",
    name: "Twilio SMS",
    type: "messaging",
    status: "connected",
    lastSync: "Real-time",
  },
  {
    id: "5",
    name: "SendGrid",
    type: "email",
    status: "connected",
    lastSync: "5 minutes ago",
  },
  {
    id: "6",
    name: "Google Calendar",
    type: "calendar",
    status: "connected",
    lastSync: "1 minute ago",
  },
  {
    id: "7",
    name: "HubSpot",
    type: "crm",
    status: "disconnected",
  },
  {
    id: "8",
    name: "Microsoft Teams",
    type: "messaging",
    status: "error",
    lastSync: "Connection failed",
  },
]

export const mockLiveConversation: LiveConversation = {
  id: "live-1",
  prospectId: "1",
  prospectName: "Khalid Abdullah",
  channel: "phone",
  status: "connected",
  duration: 127,
  sentiment: "positive",
  transcript: [
    {
      timestamp: "00:00:05",
      speaker: "agent",
      message: "Good afternoon! This is calling from First Projects Holding. Am I speaking with Khalid Abdullah?",
    },
    {
      timestamp: "00:00:12",
      speaker: "prospect",
      message: "Yes, this is Khalid speaking. How can I help you?",
    },
    {
      timestamp: "00:00:18",
      speaker: "agent",
      message:
        "Excellent! I'm reaching out regarding our exclusive luxury villa collection in Riyadh. I understand you've expressed interest in premium properties. Do you have a few moments?",
    },
    {
      timestamp: "00:00:32",
      speaker: "prospect",
      message: "Actually yes, I'm looking for something in the 3 to 5 million SAR range. What do you have available?",
    },
    {
      timestamp: "00:00:45",
      speaker: "agent",
      message:
        "Perfect! We have several stunning options. I'd particularly recommend Azure Heights Villa - a 4-bedroom with smart home integration, private pool, and 24/7 security. Would you be interested in a private viewing?",
    },
  ],
  detectedEntities: [
    { type: "budget", value: "3-5M SAR", confidence: 0.95 },
    { type: "area", value: "Riyadh", confidence: 0.92 },
    { type: "bedrooms", value: "4+", confidence: 0.78 },
    { type: "timeline", value: "3-6 months", confidence: 0.85 },
    { type: "intent", value: "High Purchase Intent", confidence: 0.89 },
  ],
  nextBestQuestion:
    "Ask about their preferred move-in timeline and whether they're considering financing options or cash purchase.",
  agentPlan: [
    {
      step: 1,
      name: "Verify Identity",
      description: "Confirm speaking with the right person",
      status: "completed",
    },
    {
      step: 2,
      name: "Build Rapport",
      description: "Establish connection and assess interest",
      status: "completed",
    },
    {
      step: 3,
      name: "Qualify Budget",
      description: "Understand financial requirements",
      status: "completed",
    },
    {
      step: 4,
      name: "Match Properties",
      description: "Present suitable options from inventory",
      status: "in_progress",
    },
    {
      step: 5,
      name: "Schedule Viewing",
      description: "Book property tour appointment",
      status: "pending",
    },
    {
      step: 6,
      name: "Log & Handoff",
      description: "Update CRM and prepare handoff package",
      status: "pending",
    },
  ],
}

// Keep mockLiveCall as alias
export const mockLiveCall = mockLiveConversation

export const mockLiveWhatsApp: LiveConversation = {
  id: "live-2",
  prospectId: "2",
  prospectName: "Fatima Al-Zahrani",
  channel: "whatsapp",
  status: "connected",
  duration: 0,
  sentiment: "positive",
  transcript: [
    {
      timestamp: "14:30",
      speaker: "agent",
      message:
        "Hello Fatima! This is the AI assistant from First Projects Holding. Thank you for your interest in our luxury properties in Jeddah. How may I assist you today?",
    },
    {
      timestamp: "14:32",
      speaker: "prospect",
      message: "Hi! I saw your Pearl Tower listing. Can you tell me more about the penthouse units?",
    },
    {
      timestamp: "14:32",
      speaker: "agent",
      message:
        "Of course! The Pearl Tower Penthouse is our flagship offering with stunning Red Sea views. It features 3 bedrooms, a private rooftop terrace, and 24/7 concierge service. The price range is 6.8M - 7.5M SAR. Would you like to see the floor plans?",
    },
    {
      timestamp: "14:35",
      speaker: "prospect",
      message: "Yes please! Also, do you have any payment plans?",
    },
  ],
  detectedEntities: [
    { type: "budget", value: "6-8M SAR", confidence: 0.88 },
    { type: "area", value: "Jeddah", confidence: 0.98 },
    { type: "intent", value: "High Purchase Intent", confidence: 0.91 },
  ],
  nextBestQuestion:
    "Share the floor plans and inquire about their financing preference - developer payment plan vs bank mortgage.",
  agentPlan: [
    { step: 1, name: "Greet & Engage", description: "Welcome and acknowledge interest", status: "completed" },
    { step: 2, name: "Present Property", description: "Share details about Pearl Tower", status: "completed" },
    { step: 3, name: "Share Media", description: "Send floor plans and virtual tour", status: "in_progress" },
    { step: 4, name: "Discuss Financing", description: "Explain payment options", status: "pending" },
    { step: 5, name: "Schedule Viewing", description: "Book site visit", status: "pending" },
  ],
}

export const mockCampaignRun: CampaignRun = {
  id: "run-1",
  campaignId: "1",
  campaignName: "Riyadh Q1 Luxury Villas",
  status: "running",
  startedAt: "2024-01-15T09:00:00",
  queue: [
    {
      id: "q1",
      prospectId: "1",
      prospectName: "Khalid Abdullah",
      phone: "+966 50 123 4567",
      channel: "phone",
      status: "connected",
      attempts: 1,
    },
    {
      id: "q2",
      prospectId: "2",
      prospectName: "Fatima Al-Zahrani",
      phone: "+966 55 234 5678",
      whatsapp: "+966 55 234 5678",
      channel: "whatsapp",
      status: "responded",
      attempts: 1,
    },
    {
      id: "q3",
      prospectId: "3",
      prospectName: "Sultan Al-Harbi",
      phone: "+966 50 345 6789",
      channel: "phone",
      status: "queued",
      attempts: 0,
    },
    {
      id: "q4",
      prospectId: "4",
      prospectName: "Mariam Al-Ghamdi",
      phone: "+966 55 456 7890",
      email: "mariam@example.com",
      channel: "email",
      status: "delivered",
      attempts: 1,
    },
    {
      id: "q5",
      prospectId: "5",
      prospectName: "Abdullah Al-Mutairi",
      phone: "+966 50 567 8901",
      channel: "phone",
      status: "completed",
      attempts: 1,
    },
  ],
  currentConversation: mockLiveConversation,
  metrics: {
    totalLeads: 150,
    contacted: 87,
    connected: 42,
    voicemails: 15,
    noAnswers: 30,
    booked: 12,
    connectRate: 48,
    byChannel: {
      phone: { contacted: 45, connected: 22 },
      whatsapp: { sent: 30, responded: 18 },
      email: { sent: 12, opened: 8 },
    },
  },
}

export const mockHandoffPackages: HandoffPackage[] = [
  {
    id: "ho-1",
    conversationId: "2",
    prospectId: "2",
    prospectName: "Fatima Al-Zahrani",
    prospectPhone: "+966 55 234 5678",
    prospectEmail: "fatima@example.com",
    prospectWhatsapp: "+966 55 234 5678",
    timestamp: "2024-01-15T11:45:00",
    priority: "high",
    sourceChannel: "whatsapp",
    suggestedFollowUpChannel: "phone",
    reason: "Complex financing questions requiring human expertise",
    summary:
      "High-value prospect interested in Pearl Tower Penthouse. Has specific questions about developer payment plans and bank financing options. Ready to proceed but needs detailed financial consultation.",
    detectedNeeds: [
      "Payment plan details",
      "Bank financing options",
      "Legal documentation",
      "Move-in timeline flexibility",
    ],
    suggestedProperties: ["Pearl Tower Penthouse", "Azure Heights Villa"],
    qualificationScore: {
      intentScore: 92,
      budgetFitScore: 85,
      urgency: "high",
      propertyMatchConfidence: 90,
      riskFlags: ["Complex financing needs"],
      overallScore: 89,
    },
    conversationContext:
      "24-message WhatsApp conversation. Prospect showed strong interest in Pearl Tower, requested floor plans and payment details. Questions became technical regarding mortgage vs developer financing.",
    nextSteps: [
      "Call to discuss financing options",
      "Prepare payment plan comparison",
      "Schedule property viewing",
      "Connect with finance team",
    ],
    status: "pending",
  },
  {
    id: "ho-2",
    conversationId: "5",
    prospectId: "5",
    prospectName: "Abdullah Al-Mutairi",
    prospectPhone: "+966 50 567 8901",
    prospectEmail: "abdullah.m@example.com",
    prospectWhatsapp: "+966 50 567 8901",
    timestamp: "2024-01-15T15:30:00",
    priority: "high",
    sourceChannel: "phone",
    suggestedFollowUpChannel: "phone",
    reason: "VIP prospect requesting exclusive properties",
    summary:
      "Ultra-high-net-worth individual interested in Royal Palm Estate. Looking for immediate purchase with cash. Requesting private viewing with senior management.",
    detectedNeeds: ["Exclusive property access", "VIP treatment", "Senior management meeting", "Quick closing process"],
    suggestedProperties: ["Royal Palm Estate"],
    qualificationScore: {
      intentScore: 95,
      budgetFitScore: 92,
      urgency: "high",
      propertyMatchConfidence: 94,
      riskFlags: [],
      overallScore: 94,
    },
    conversationContext:
      "9-minute call. Prospect directly asked for the most exclusive property available. Mentioned cash purchase and requested meeting with company leadership.",
    nextSteps: [
      "Arrange CEO introduction",
      "Schedule private estate viewing",
      "Prepare bespoke presentation",
      "Fast-track documentation",
    ],
    status: "claimed",
    claimedBy: "Mohammed Al-Farsi",
    claimedAt: "2024-01-15T15:45:00",
  },
  {
    id: "ho-3",
    conversationId: "8",
    prospectId: "8",
    prospectName: "Sara Al-Qahtani",
    prospectPhone: "+966 55 890 1234",
    prospectEmail: "sara.q@example.com",
    prospectWhatsapp: "+966 55 890 1234",
    timestamp: "2024-01-14T10:30:00",
    priority: "medium",
    sourceChannel: "phone",
    suggestedFollowUpChannel: "whatsapp",
    reason: "Family decision - needs spouse involvement",
    summary:
      "Interested in Royal Palm Estate but needs to consult with spouse. Requested materials to share and follow-up in a week.",
    detectedNeeds: [
      "Family consultation time",
      "Shareable materials",
      "Flexible viewing schedule",
      "Child-friendly features",
    ],
    suggestedProperties: ["Royal Palm Estate", "Golden Oasis Residence"],
    qualificationScore: {
      intentScore: 88,
      budgetFitScore: 95,
      urgency: "medium",
      propertyMatchConfidence: 85,
      riskFlags: ["Decision maker unclear"],
      overallScore: 89,
    },
    conversationContext:
      "6-minute call. Strong interest but explicitly mentioned needing spouse approval. Asked about family amenities and schools nearby.",
    nextSteps: [
      "Send digital brochure via WhatsApp",
      "Schedule follow-up in 5 days",
      "Include family amenities info",
      "Offer family viewing",
    ],
    status: "pending",
  },
  {
    id: "ho-4",
    conversationId: "7",
    prospectId: "7",
    prospectName: "Nasser Al-Otaibi",
    prospectPhone: "+966 50 789 0123",
    prospectEmail: "nasser@example.com",
    prospectWhatsapp: "+966 50 789 0123",
    timestamp: "2024-01-15T17:00:00",
    priority: "medium",
    sourceChannel: "whatsapp",
    suggestedFollowUpChannel: "whatsapp",
    reason: "Investment property inquiry - needs ROI discussion",
    summary:
      "Investor interested in rental yield potential. Looking at multiple units for investment portfolio. Needs detailed ROI analysis.",
    detectedNeeds: ["ROI projections", "Rental yield data", "Multiple unit pricing", "Investment portfolio advice"],
    suggestedProperties: ["Golden Oasis Residence", "Coral Bay Apartments"],
    qualificationScore: {
      intentScore: 82,
      budgetFitScore: 88,
      urgency: "medium",
      propertyMatchConfidence: 80,
      riskFlags: ["Investment buyer - longer decision cycle"],
      overallScore: 83,
    },
    conversationContext:
      "18-message WhatsApp thread. Prospect is building investment portfolio. Asked detailed questions about rental market and expected returns.",
    nextSteps: [
      "Prepare investment analysis",
      "Share rental yield data",
      "Offer bulk purchase incentives",
      "Connect with investment advisor",
    ],
    status: "pending",
  },
  {
    id: "ho-5",
    conversationId: "1",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    prospectPhone: "+966 50 123 4567",
    prospectEmail: "khalid@example.com",
    prospectWhatsapp: "+966 50 123 4567",
    timestamp: "2024-01-15T11:00:00",
    priority: "high",
    sourceChannel: "phone",
    suggestedFollowUpChannel: "phone",
    reason: "Ready to book viewing - high intent",
    summary:
      "Qualified lead ready for property viewing. Showed strong interest in Azure Heights Villa. Has budget confirmed and timeline of 3-6 months.",
    detectedNeeds: ["Property viewing", "Smart home demonstration", "Pool and garden tour", "Security briefing"],
    suggestedProperties: ["Azure Heights Villa", "Golden Oasis Residence"],
    qualificationScore: {
      intentScore: 85,
      budgetFitScore: 90,
      urgency: "high",
      propertyMatchConfidence: 88,
      riskFlags: [],
      overallScore: 87,
    },
    conversationContext:
      "7-minute call. Very engaged, asked specific questions about smart home features and security. Ready to schedule viewing.",
    nextSteps: [
      "Confirm viewing appointment",
      "Prepare property presentation",
      "Arrange smart home demo",
      "Send location and parking details",
    ],
    status: "completed",
    claimedBy: "Mohammed Al-Farsi",
    claimedAt: "2024-01-15T11:15:00",
  },
]

export const mockRoutingRules: RoutingRule[] = [
  {
    id: "1",
    name: "VIP Riyadh Routing",
    conditions: [
      { field: "city", operator: "equals", value: "Riyadh" },
      { field: "budget", operator: "greaterThan", value: "10000000" },
    ],
    assignTo: "3",
    priority: 1,
    enabled: true,
  },
  {
    id: "2",
    name: "Jeddah Leads",
    conditions: [{ field: "city", operator: "equals", value: "Jeddah" }],
    assignTo: "4",
    priority: 2,
    enabled: true,
  },
  {
    id: "3",
    name: "WhatsApp Preference",
    conditions: [{ field: "channel", operator: "equals", value: "whatsapp" }],
    assignTo: "auto",
    priority: 3,
    enabled: true,
  },
]
