import type {
  User,
  Prospect,
  Property,
  Conversation,
  Campaign,
  Appointment,
  Integration,
  LiveConversation,
  CampaignRun,
  RoutingRule,
  HandoffPackage,
  Channel,
} from "./types"

export function getChannelIcon(channel: Channel): string {
  const icons: Record<Channel, string> = {
    phone: "Phone",
    whatsapp: "MessageCircle",
    sms: "MessageSquare",
    email: "Mail",
  }
  return icons[channel]
}

export function getChannelColor(channel: Channel): string {
  const colors: Record<Channel, string> = {
    phone: "bg-blue-500/20 text-blue-500 border-blue-500/30",
    whatsapp: "bg-emerald-500/20 text-emerald-500 border-emerald-500/30",
    sms: "bg-violet-500/20 text-violet-500 border-violet-500/30",
    email: "bg-amber-500/20 text-amber-500 border-amber-500/30",
  }
  return colors[channel]
}

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ahmed Al-Mansour",
    email: "ahmed@fph.sa",
    role: "admin",
    status: "active",
    lastActive: "2 minutes ago",
  },
  {
    id: "2",
    name: "Sarah Al-Rashid",
    email: "sarah@fph.sa",
    role: "sales_manager",
    status: "active",
    lastActive: "15 minutes ago",
  },
  {
    id: "3",
    name: "Mohammed Al-Farsi",
    email: "mohammed@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "1 hour ago",
  },
  {
    id: "4",
    name: "Layla Hassan",
    email: "layla@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "30 minutes ago",
  },
  {
    id: "5",
    name: "Omar Al-Saud",
    email: "omar@fph.sa",
    role: "qa_supervisor",
    status: "active",
    lastActive: "2 hours ago",
  },
  {
    id: "6",
    name: "Noor Al-Khaled",
    email: "noor@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "45 minutes ago",
  },
  {
    id: "7",
    name: "Yusuf Al-Najjar",
    email: "yusuf@fph.sa",
    role: "compliance_officer",
    status: "active",
    lastActive: "3 hours ago",
  },
  {
    id: "8",
    name: "Amira Khalil",
    email: "amira@fph.sa",
    role: "sales_manager",
    status: "active",
    lastActive: "1 hour ago",
  },
  {
    id: "9",
    name: "Faisal Al-Dossary",
    email: "faisal@fph.sa",
    role: "sales_rep",
    status: "inactive",
    lastActive: "2 days ago",
  },
  {
    id: "10",
    name: "Hana Al-Qasim",
    email: "hana@fph.sa",
    role: "operations",
    status: "active",
    lastActive: "20 minutes ago",
  },
  {
    id: "11",
    name: "Ibrahim Al-Tamimi",
    email: "ibrahim@fph.sa",
    role: "sales_rep",
    status: "active",
    lastActive: "10 minutes ago",
  },
  {
    id: "12",
    name: "Maha Al-Shehri",
    email: "maha@fph.sa",
    role: "qa_supervisor",
    status: "active",
    lastActive: "5 hours ago",
  },
]

export const mockProspects: Prospect[] = [
  {
    id: "1",
    name: "Khalid Abdullah",
    email: "khalid@example.com",
    phone: "+966 50 123 4567",
    whatsapp: "+966 50 123 4567",
    budget: "3-5M SAR",
    city: "Riyadh",
    timeline: "3-6 months",
    status: "qualified",
    assignedTo: "3",
    lastContact: "2024-01-15",
    preferredChannel: "whatsapp",
  },
  {
    id: "2",
    name: "Fatima Al-Zahrani",
    email: "fatima@example.com",
    phone: "+966 55 234 5678",
    whatsapp: "+966 55 234 5678",
    budget: "5-8M SAR",
    city: "Jeddah",
    timeline: "1-3 months",
    status: "appointment_set",
    assignedTo: "3",
    lastContact: "2024-01-14",
    preferredChannel: "phone",
  },
  {
    id: "3",
    name: "Sultan Al-Harbi",
    email: "sultan@example.com",
    phone: "+966 50 345 6789",
    whatsapp: "+966 50 345 6789",
    budget: "8-12M SAR",
    city: "Riyadh",
    timeline: "6-12 months",
    status: "contacted",
    assignedTo: "4",
    lastContact: "2024-01-13",
    preferredChannel: "email",
  },
  {
    id: "4",
    name: "Mariam Al-Ghamdi",
    email: "mariam@example.com",
    phone: "+966 55 456 7890",
    whatsapp: "+966 55 456 7890",
    budget: "4-6M SAR",
    city: "Dammam",
    timeline: "1-3 months",
    status: "qualified",
    assignedTo: "6",
    lastContact: "2024-01-15",
    preferredChannel: "whatsapp",
  },
  {
    id: "5",
    name: "Abdullah Al-Mutairi",
    email: "abdullah.m@example.com",
    phone: "+966 50 567 8901",
    whatsapp: "+966 50 567 8901",
    budget: "10-15M SAR",
    city: "Riyadh",
    timeline: "3-6 months",
    status: "appointment_set",
    assignedTo: "3",
    lastContact: "2024-01-14",
    preferredChannel: "phone",
  },
  {
    id: "6",
    name: "Aisha Al-Harthi",
    email: "aisha@example.com",
    phone: "+966 55 678 9012",
    budget: "2-4M SAR",
    city: "Jeddah",
    timeline: "6-12 months",
    status: "new",
    assignedTo: "4",
    lastContact: "2024-01-12",
    preferredChannel: "sms",
  },
  {
    id: "7",
    name: "Nasser Al-Otaibi",
    email: "nasser@example.com",
    phone: "+966 50 789 0123",
    whatsapp: "+966 50 789 0123",
    budget: "6-9M SAR",
    city: "Riyadh",
    timeline: "1-3 months",
    status: "qualified",
    assignedTo: "11",
    lastContact: "2024-01-15",
    preferredChannel: "whatsapp",
  },
  {
    id: "8",
    name: "Sara Al-Qahtani",
    email: "sara.q@example.com",
    phone: "+966 55 890 1234",
    whatsapp: "+966 55 890 1234",
    budget: "15-20M SAR",
    city: "Riyadh",
    timeline: "1-3 months",
    status: "qualified",
    assignedTo: "3",
    lastContact: "2024-01-15",
    preferredChannel: "phone",
  },
  {
    id: "9",
    name: "Turki Al-Shamrani",
    email: "turki@example.com",
    phone: "+966 50 901 2345",
    budget: "5-7M SAR",
    city: "Jeddah",
    timeline: "3-6 months",
    status: "contacted",
    assignedTo: "6",
    lastContact: "2024-01-14",
    preferredChannel: "email",
  },
  {
    id: "10",
    name: "Noura Al-Dosari",
    email: "noura@example.com",
    phone: "+966 55 012 3456",
    whatsapp: "+966 55 012 3456",
    budget: "8-10M SAR",
    city: "Dammam",
    timeline: "6-12 months",
    status: "new",
    assignedTo: "4",
    lastContact: "2024-01-13",
    preferredChannel: "whatsapp",
  },
]

export const mockProperties: Property[] = [
  {
    id: "8bfa2ac4-74fc-49f3-b5a1-7d904266ff9a",
    name: "Azure Heights Villa",
    city: "Riyadh",
    priceRange: "4.5M - 5.2M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Contemporary 4-bedroom villa with elegant finishes and a calm, private setting in Riyadh.",
    features: ["Private garden", "En-suite bedrooms", "Chef kitchen", "Maid room", "Smart lighting"],
    imageUrl: "/luxury-modern-villa-with-pool-riyadh.jpg",
  },
  {
    id: "2ae019c0-26bc-464a-ba52-aab15212e7bc",
    name: "Pearl Tower Penthouse",
    city: "Jeddah",
    priceRange: "6.8M - 7.5M SAR",
    bedrooms: 3,
    type: "penthouse",
    status: "available",
    description: "High-floor penthouse with expansive entertaining spaces and premium detailing in Jeddah.",
    features: ["Panoramic views", "Private terrace", "Floor-to-ceiling windows", "Designer finishes", "Private lift lobby"],
    imageUrl: "/luxury-penthouse-sea-view-jeddah.jpg",
  },
  {
    id: "2ba45a3e-33f0-41f7-97d9-e42eb6248aba",
    name: "Golden Oasis Residence",
    city: "Riyadh",
    priceRange: "3.2M - 3.8M SAR",
    bedrooms: 3,
    type: "villa",
    status: "available",
    description: "Bright 3-bedroom villa designed for comfortable family living with modern interiors.",
    features: ["Family lounge", "En-suite bedrooms", "Modern kitchen", "Storage room", "Outdoor sitting area"],
    imageUrl: "/modern-villa-gated-community-riyadh.jpg",
  },
  {
    id: "22e82ca1-965e-4f30-98f7-8b30ad58571e",
    name: "Coral Bay Apartments",
    city: "Dammam",
    priceRange: "1.8M - 2.4M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Modern 2-bedroom apartment with a practical layout and clean contemporary style.",
    features: ["Open-plan living", "Balcony", "Built-in wardrobes", "Modern kitchen", "Natural light"],
    imageUrl: "/waterfront-apartment-dammam-bay-view.jpg",
  },
  {
    id: "f52467c9-84e5-4ed6-b15d-ee1a8b0c56d7",
    name: "Royal Palm Estate",
    city: "Riyadh",
    priceRange: "12M - 15M SAR",
    bedrooms: 6,
    type: "villa",
    status: "available",
    description: "Statement 6-bedroom estate villa with grand volumes and premium indoor-outdoor living.",
    features: ["Private pool", "Home elevator", "Majlis", "Chef kitchen", "Cinema room"],
    imageUrl: "/ultra-luxury-mansion-estate-riyadh.jpg",
  },
  {
    id: "45990c2d-7f4a-42bd-9edf-f82aa6eec791",
    name: "Sapphire Towers",
    city: "Jeddah",
    priceRange: "2.1M - 2.6M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Stylish 2-bedroom apartment with great flow, modern finishes, and a bright living area.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "City views"],
    imageUrl: "/modern-high-rise-apartment-jeddah-city.jpg",
  },
  {
    id: "5378ff70-7970-4d44-ae53-f85dda2d95a0",
    name: "Desert Rose Villa",
    city: "Riyadh",
    priceRange: "5.8M - 6.5M SAR",
    bedrooms: 5,
    type: "villa",
    status: "reserved",
    description: "Spacious 5-bedroom villa with generous family zones and refined, modern materials.",
    features: ["Private garden", "En-suite bedrooms", "Maid room", "Formal dining", "Smart home wiring"],
    imageUrl: "/arabian-traditional-villa-riyadh.jpg",
  },
  {
    id: "a03154ea-bec0-45d3-942e-3c8e9a65eae1",
    name: "Marina Vista Penthouse",
    city: "Dammam",
    priceRange: "4.2M - 4.8M SAR",
    bedrooms: 4,
    type: "penthouse",
    status: "available",
    description: "Luxury penthouse with wide living spaces and a premium, airy feel in Dammam.",
    features: ["Large terrace", "Panoramic windows", "Designer finishes", "Private lift access", "Entertaining lounge"],
    imageUrl: "/marina-penthouse-arabian-gulf-view.jpg",
  },
  {
    id: "7b2cccd5-b600-444e-8a37-f89c89894c8d",
    name: "Emerald Gardens Townhouse",
    city: "Riyadh",
    priceRange: "2.8M - 3.3M SAR",
    bedrooms: 3,
    type: "townhouse",
    status: "available",
    description: "Modern 3-bedroom townhouse in a community setting—great for families seeking space and privacy.",
    features: ["Private courtyard", "Rooftop terrace", "Family lounge", "Modern kitchen", "Storage room"],
    imageUrl: "/modern-townhouse-garden-riyadh.jpg",
  },
  {
    id: "11b8424f-d226-4be7-b44d-f50519d5e68d",
    name: "Crystal Palace Residence",
    city: "Jeddah",
    priceRange: "8.5M - 9.2M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Premium 5-bedroom villa with polished finishes and an impressive entertaining layout.",
    features: ["Private pool", "Majlis", "Chef kitchen", "Maid room", "Premium stone finishes"],
    imageUrl: "/palatial-luxury-villa-marble-jeddah.jpg",
  },
  {
    id: "8dad6e6e-2344-4ea4-9d75-162834cc877b",
    name: "Horizon Heights",
    city: "Riyadh",
    priceRange: "1.5M - 1.9M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Well-designed 2-bedroom apartment with modern style and excellent everyday practicality.",
    features: ["Open-plan living", "Balcony", "Modern kitchen", "Built-in wardrobes", "Bright interiors"],
    imageUrl: "/affordable-modern-apartment-riyadh.jpg",
  },
  {
    id: "3ab706f1-b9fe-4a7f-9ecd-3782b7cc748a",
    name: "Platinum Residence",
    city: "Dammam",
    priceRange: "3.5M - 4.1M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Contemporary 4-bedroom villa with clean lines, functional spaces, and premium finishes.",
    features: ["Private garden", "En-suite bedrooms", "Family lounge", "Maid room", "Modern kitchen"],
    imageUrl: "/contemporary-villa-modern-design-dammam.jpg",
  },
  {
    id: "7a2d35bf-15d2-40c3-8cf3-ac028c81258a",
    name: "Silver Dunes Estate",
    city: "Riyadh",
    priceRange: "7.2M - 8.0M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Elegant 5-bedroom villa offering a refined lifestyle with spacious interiors and privacy.",
    features: ["Private pool", "En-suite bedrooms", "Majlis", "Maid room", "Smart lighting"],
    imageUrl: "/spacious-villa-modern-traditional-riyadh.jpg",
  },
  {
    id: "cf747c41-4c2b-4ad8-ba6f-dcf8b8d1d8a2",
    name: "Amber Towers",
    city: "Jeddah",
    priceRange: "2.9M - 3.4M SAR",
    bedrooms: 3,
    type: "apartment",
    status: "sold",
    description: "A popular 3-bedroom apartment line known for strong layouts and excellent building services.",
    features: ["Open-plan living", "Balcony", "Built-in wardrobes", "Modern kitchen", "City views"],
    imageUrl: "/apartment-red-sea-view-jeddah.jpg",
  },
  {
    id: "cfc02b93-4ade-4552-a8cb-79470d33aba0",
    name: "Oasis Springs Villa",
    city: "Riyadh",
    priceRange: "4.0M - 4.7M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "4-bedroom villa with airy living areas and a balanced indoor-outdoor lifestyle.",
    features: ["Private garden", "En-suite bedrooms", "Family lounge", "Maid room", "Chef kitchen"],
    imageUrl: "/villa-water-features-landscaping-riyadh.jpg",
  },
  {
    id: "c4b07cd2-c157-4f54-8ffb-4454e8da76fc",
    name: "Diamond District Loft",
    city: "Dammam",
    priceRange: "2.2M - 2.7M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Upscale 1-bedroom loft-style apartment with modern finishes and a premium feel.",
    features: ["Loft layout", "High ceilings", "Modern kitchen", "Built-in wardrobes", "City views"],
    imageUrl: "/modern-high-rise-apartment-jeddah-city.jpg",
  },
  {
    id: "c89c86b1-35cb-4b3e-b291-42c658c3dc67",
    name: "Royal Gardens Mansion",
    city: "Riyadh",
    priceRange: "18M - 22M SAR",
    bedrooms: 7,
    type: "villa",
    status: "available",
    description: "Grand 7-bedroom mansion offering exceptional scale, privacy, and luxury entertaining spaces.",
    features: ["Private pool", "Home elevator", "Cinema room", "Grand majlis", "Landscaped gardens"],
    imageUrl: "/ultra-luxury-mansion-estate-riyadh.jpg",
  },
  {
    id: "364d6e62-7786-49ec-867c-b98506319e85",
    name: "Sunset Boulevard Penthouse",
    city: "Jeddah",
    priceRange: "5.5M - 6.2M SAR",
    bedrooms: 3,
    type: "penthouse",
    status: "reserved",
    description: "High-end penthouse with sunset-facing terraces and premium building services in Jeddah.",
    features: ["Private terrace", "Floor-to-ceiling windows", "Designer finishes", "Private lift access", "Open-plan lounge"],
    imageUrl: "/luxury-penthouse-sea-view-jeddah.jpg",
  },
  {
    id: "bc5e900e-ab88-4249-a1f8-033e6c6bd5b6",
    name: "Green Valley Townhouse",
    city: "Riyadh",
    priceRange: "2.5M - 2.9M SAR",
    bedrooms: 3,
    type: "townhouse",
    status: "available",
    description: "Comfortable 3-bedroom townhouse with family-friendly layout and community amenities.",
    features: ["Private courtyard", "Family lounge", "Modern kitchen", "Storage room", "Rooftop terrace"],
    imageUrl: "/modern-townhouse-garden-riyadh.jpg",
  },
  {
    id: "0a7134ba-edbe-4438-819a-ae97abcb26ca",
    name: "Coastal Breeze Apartment",
    city: "Dammam",
    priceRange: "1.6M - 2.0M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Bright 2-bedroom apartment with coastal-city convenience and modern finishes.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "Bright interiors"],
    imageUrl: "/waterfront-apartment-dammam-bay-view.jpg",
  },
  {
    id: "a9b127c2-6908-4ed0-b8be-ad05b6b6bfd0",
    name: "Paradise Hills Villa",
    city: "Jeddah",
    priceRange: "6.5M - 7.2M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Luxury 5-bedroom villa with impressive interiors and elegant, family-focused design.",
    features: ["Private pool", "Majlis", "Chef kitchen", "Maid room", "Premium finishes"],
    imageUrl: "/luxury-modern-villa-with-pool-riyadh.jpg",
  },
  {
    id: "ba676b37-3183-46f1-a443-c7234dd9270c",
    name: "Metropolitan Square",
    city: "Riyadh",
    priceRange: "2.7M - 3.2M SAR",
    bedrooms: 3,
    type: "apartment",
    status: "available",
    description: "Modern 3-bedroom apartment with a generous living area and contemporary styling.",
    features: ["Open-plan living", "Balcony", "Modern kitchen", "Built-in wardrobes", "City views"],
    imageUrl: "/affordable-modern-apartment-riyadh.jpg",
  },
  {
    id: "d41d7b56-02c7-4ed3-b1b0-1e289c8ca67a",
    name: "Heritage Palace",
    city: "Riyadh",
    priceRange: "15M - 18M SAR",
    bedrooms: 6,
    type: "villa",
    status: "available",
    description: "Prestige 6-bedroom villa with grand proportions and a premium, private setting.",
    features: ["Private pool", "Home elevator", "Majlis", "Chef kitchen", "Cinema room"],
    imageUrl: "/arabian-traditional-villa-riyadh.jpg",
  },
  {
    id: "a90e05bd-261c-413a-a00a-2594d4762504",
    name: "Azure Bay Residences",
    city: "Dammam",
    priceRange: "3.8M - 4.4M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Contemporary 4-bedroom villa offering comfort, privacy, and clean modern design.",
    features: ["Private garden", "En-suite bedrooms", "Family lounge", "Maid room", "Modern kitchen"],
    imageUrl: "/waterfront-apartment-dammam-bay-view.jpg",
  },
  {
    id: "92c9ada5-81c5-437a-870a-81f18451a13e",
    name: "Skyline Tower Penthouse",
    city: "Riyadh",
    priceRange: "9.5M - 11M SAR",
    bedrooms: 4,
    type: "penthouse",
    status: "available",
    description: "Signature 4-bedroom penthouse with panoramic skyline views and refined luxury finishes.",
    features: ["Panoramic views", "Private terrace", "Private lift lobby", "Designer finishes", "Entertaining lounge"],
    imageUrl: "/marina-penthouse-arabian-gulf-view.jpg",
  },
  // New properties (26-50)
  {
    id: "f40d8367-d5e0-43f3-a46e-d99c0dda84f3",
    name: "Cedar Court Apartments",
    city: "Riyadh",
    priceRange: "1.25M - 1.55M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Modern 1-bedroom apartment with a clean layout and bright, comfortable living space.",
    features: ["Open-plan living", "Built-in wardrobes", "Modern kitchen", "Large windows", "Efficient layout"],
    imageUrl: "/cedar-court-apartments.jpg",
  },
  {
    id: "c531cd20-b960-4e08-949d-bdccae7a077b",
    name: "Al Noor Starter Homes",
    city: "Riyadh",
    priceRange: "1.85M - 2.2M SAR",
    bedrooms: 2,
    type: "townhouse",
    status: "available",
    description: "Starter-friendly 2-bedroom townhouse with private outdoor space and smart layout.",
    features: ["Private courtyard", "Family lounge", "Modern kitchen", "Storage room", "Rooftop terrace"],
    imageUrl: "/al-noor-starter-homes.jpg",
  },
  {
    id: "d66df03b-ebcf-4fa1-93d5-f0848a8562f0",
    name: "Metro Edge Residences",
    city: "Riyadh",
    priceRange: "2.1M - 2.6M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Sleek 2-bedroom apartment designed for modern city living with an airy open-plan flow.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "City views"],
    imageUrl: "/metro-edge-residences.jpg",
  },
  {
    id: "219c03e8-e683-434f-b379-753f09b6e7e1",
    name: "Business Bay Suites",
    city: "Riyadh",
    priceRange: "1.6M - 2.05M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Upscale 1-bedroom apartment near business hubs—ideal for executives and investors.",
    features: ["City views", "Modern kitchen", "Built-in wardrobes", "Open-plan living", "Work-friendly nook"],
    imageUrl: "/business-bay-suites.jpg",
  },
  {
    id: "719c3095-011d-47be-8bd1-ef346f2f4477",
    name: "Wadi Vista Townhomes",
    city: "Riyadh",
    priceRange: "2.3M - 2.85M SAR",
    bedrooms: 3,
    type: "townhouse",
    status: "available",
    description: "Family-ready 3-bedroom townhouse with flexible living zones and quality finishes.",
    features: ["Private courtyard", "Family lounge", "Rooftop terrace", "Storage room", "Modern kitchen"],
    imageUrl: "/wadi-vista-townhomes.jpg",
  },
  {
    id: "e6046326-c7b1-481b-aff6-047ee5e2c4d7",
    name: "Kingdom Skyline Penthouse",
    city: "Riyadh",
    priceRange: "11.5M - 13.8M SAR",
    bedrooms: 4,
    type: "penthouse",
    status: "available",
    description: "Ultra-premium 4-bedroom penthouse with commanding skyline views and elite detailing.",
    features: ["Private terrace", "Panoramic windows", "Private lift lobby", "Designer finishes", "Entertaining lounge"],
    imageUrl: "/kingdom-skyline-penthouse.jpg",
  },
  {
    id: "f07b1c1a-3b58-47d7-9b87-a580c7629822",
    name: "Opal Ridge Villa",
    city: "Riyadh",
    priceRange: "6.2M - 7.1M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Luxury 5-bedroom villa offering generous space, privacy, and refined modern materials.",
    features: ["Private pool", "Majlis", "Chef kitchen", "Maid room", "Smart lighting"],
    imageUrl: "/opal-ridge-villa.jpg",
  },
  {
    id: "25d6f030-a8b7-4983-b721-183f34779053",
    name: "Palm Crest Apartments",
    city: "Riyadh",
    priceRange: "1.95M - 2.4M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Bright 2-bedroom apartment with a comfortable layout and modern finishes throughout.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "Bright interiors"],
    imageUrl: "/palm-crest-apartments.jpg",
  },
  {
    id: "85fee28d-88db-42fd-b68a-77badd9159bd",
    name: "Corniche Pearl Apartments",
    city: "Jeddah",
    priceRange: "2.4M - 2.95M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Coastal-inspired 2-bedroom apartment near the corniche with an airy, relaxed vibe.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "Sea-breeze feel"],
    imageUrl: "/corniche-pearl-apartments.jpg",
  },
  {
    id: "fd22c690-7b4a-48c6-8bd0-e774ede7a57f",
    name: "Red Sea Panorama Penthouse",
    city: "Jeddah",
    priceRange: "7.8M - 9.1M SAR",
    bedrooms: 3,
    type: "penthouse",
    status: "available",
    description: "Penthouse with dramatic Red Sea-facing views and premium entertaining spaces.",
    features: ["Panoramic views", "Private terrace", "Floor-to-ceiling windows", "Designer finishes", "Private lift lobby"],
    imageUrl: "/red-sea-panorama-penthouse.jpg",
  },
  {
    id: "1243d28a-3cbc-411c-8a33-b89793177007",
    name: "Marina Gate Residences",
    city: "Jeddah",
    priceRange: "3.1M - 3.85M SAR",
    bedrooms: 3,
    type: "apartment",
    status: "available",
    description: "Modern 3-bedroom residence with a family-friendly plan and a bright living area.",
    features: ["Balcony", "Large living room", "Modern kitchen", "Built-in wardrobes", "Smart-ready wiring"],
    imageUrl: "/marina-gate-residences.jpg",
  },
  {
    id: "bb79db6f-46b2-4b6c-ac76-511202fa822e",
    name: "Al Rawdah Modern Villa",
    city: "Jeddah",
    priceRange: "6.9M - 8.2M SAR",
    bedrooms: 5,
    type: "villa",
    status: "available",
    description: "Premium 5-bedroom modern villa with elegant finishes and private outdoor living.",
    features: ["Private pool", "Majlis", "Chef kitchen", "Maid room", "Premium finishes"],
    imageUrl: "/al-rawdah-modern-villa.jpg",
  },
  {
    id: "2de9d937-30f1-43c9-97be-0fe91cf62a6d",
    name: "Sunlit Courtyard Villa",
    city: "Jeddah",
    priceRange: "5.6M - 6.7M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Courtyard-focused 4-bedroom villa designed for privacy, light, and relaxed entertaining.",
    features: ["Private courtyard", "Water feature", "En-suite bedrooms", "Chef kitchen", "Maid room"],
    imageUrl: "/sunlit-courtyard-villa.jpg",
  },
  {
    id: "59c70a97-dd49-4d81-849b-e8f1e32fc4ae",
    name: "Historic District Loft Apartments",
    city: "Jeddah",
    priceRange: "1.7M - 2.1M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Chic 1-bedroom loft-style apartment blending modern comfort with warm, characterful design.",
    features: ["Loft layout", "Warm textures", "Modern kitchen", "Built-in wardrobes", "Feature lighting"],
    imageUrl: "/historic-district-loft-apartments.jpg",
  },
  {
    id: "79f02526-cd70-4dc9-9e25-2fb93700a0ce",
    name: "Seabreeze Starter Apartments",
    city: "Jeddah",
    priceRange: "1.55M - 1.95M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "A tidy, airy 1-bedroom starter apartment with modern finishes and low-maintenance living.",
    features: ["Open-plan living", "Modern kitchen", "Built-in wardrobes", "Bright interiors", "Efficient layout"],
    imageUrl: "/seabreeze-starter-apartments.jpg",
  },
  {
    id: "d77dd3bc-0bec-4804-9a1d-058e6283bf59",
    name: "Jeddah Crown Residence",
    city: "Jeddah",
    priceRange: "9.8M - 12M SAR",
    bedrooms: 6,
    type: "villa",
    status: "reserved",
    description: "Grand 6-bedroom villa with premium entertaining spaces and a prestigious presence.",
    features: ["Private pool", "Home elevator", "Grand majlis", "Chef kitchen", "Cinema room"],
    imageUrl: "/jeddah-crown-residence.jpg",
  },
  {
    id: "f09afddb-53c8-4f8a-b787-b4d55a55208a",
    name: "Harbor View Apartments",
    city: "Jeddah",
    priceRange: "2.05M - 2.55M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Modern 2-bedroom apartment with a bright interior and convenient access to key areas.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "Bright interiors"],
    imageUrl: "/harbor-view-apartments.jpg",
  },
  {
    id: "28595f7f-117a-432a-be5b-726db584af67",
    name: "Gulf Horizon Apartments",
    city: "Dammam",
    priceRange: "1.35M - 1.75M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Modern 1-bedroom apartment with a simple, efficient plan and contemporary finishes.",
    features: ["Open-plan living", "Modern kitchen", "Built-in wardrobes", "Large windows", "Efficient layout"],
    imageUrl: "/gulf-horizon-apartments.jpg",
  },
  {
    id: "17d7b92d-bc94-49a8-a000-8642fbb494ae",
    name: "Seaside Circuit Residences",
    city: "Dammam",
    priceRange: "2.2M - 2.85M SAR",
    bedrooms: 2,
    type: "apartment",
    status: "available",
    description: "Comfortable 2-bedroom residence with modern interiors and a balanced everyday layout.",
    features: ["Balcony", "Open-plan living", "Modern kitchen", "Built-in wardrobes", "Bright interiors"],
    imageUrl: "/seaside-circuit-residences.jpg",
  },
  {
    id: "0599daf8-761c-4487-a50e-f3320e98541c",
    name: "Pearl Coast Villa",
    city: "Dammam",
    priceRange: "4.6M - 5.4M SAR",
    bedrooms: 4,
    type: "villa",
    status: "available",
    description: "Luxury 4-bedroom villa with refined interiors and an easy indoor-outdoor lifestyle.",
    features: ["Private pool", "Private garden", "En-suite bedrooms", "Maid room", "Chef kitchen"],
    imageUrl: "/pearl-coast-villa.jpg",
  },
  {
    id: "48678724-19b9-4df1-aa24-0b370c34d36f",
    name: "Portside Investors Apartments",
    city: "Dammam",
    priceRange: "1.45M - 1.9M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "available",
    description: "Investor-friendly 1-bedroom apartment with strong layout efficiency and modern styling.",
    features: ["Efficient layout", "Modern kitchen", "Built-in wardrobes", "Bright interiors", "Work-friendly nook"],
    imageUrl: "/portside-investors-apartments.jpg",
  },
  {
    id: "c94c8ea0-aa9a-473d-b9aa-93cc8dc6ae63",
    name: "Azure Quay Penthouse",
    city: "Dammam",
    priceRange: "5.1M - 6.0M SAR",
    bedrooms: 4,
    type: "penthouse",
    status: "available",
    description: "High-end 4-bedroom penthouse with generous living zones and premium detailing.",
    features: ["Panoramic windows", "Private terrace", "Private lift lobby", "Designer finishes", "Entertaining lounge"],
    imageUrl: "/azure-quay-penthouse.jpg",
  },
  {
    id: "6ab17b74-e906-457c-abfe-1dcd666583e2",
    name: "Saffron Gate Villa",
    city: "Riyadh",
    priceRange: "8.4M - 9.7M SAR",
    bedrooms: 6,
    type: "villa",
    status: "available",
    description: "Prestige 6-bedroom villa with strong curb appeal, large interiors, and luxury comfort.",
    features: ["Private pool", "Home elevator", "Majlis", "Chef kitchen", "Maid room"],
    imageUrl: "/saffron-gate-villa.jpg",
  },
  {
    id: "a0cdac8d-d2a3-4ce1-b749-1a7b1623ecfc",
    name: "Mirage Park Apartments",
    city: "Riyadh",
    priceRange: "1.4M - 1.8M SAR",
    bedrooms: 1,
    type: "apartment",
    status: "sold",
    description: "Popular 1-bedroom apartment layout known for strong demand and practical living.",
    features: ["Open-plan living", "Modern kitchen", "Built-in wardrobes", "Bright interiors", "Efficient layout"],
    imageUrl: "/mirage-park-apartments.jpg",
  },
  {
    id: "c30707c3-f698-4317-8b95-08c2d62b85d0",
    name: "Orchid Terrace Apartments",
    city: "Jeddah",
    priceRange: "2.65M - 3.25M SAR",
    bedrooms: 3,
    type: "apartment",
    status: "available",
    description: "Spacious 3-bedroom apartment designed for family comfort with a generous living area.",
    features: ["Large living room", "Balcony", "Modern kitchen", "Built-in wardrobes", "Family-friendly layout"],
    imageUrl: "/orchid-terrace-apartments.jpg",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "1",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    campaignId: "1",
    timestamp: "2024-01-15T10:30:00",
    duration: 420,
    channel: "phone",
    outcome: "qualified",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: false,
    qualificationScore: {
      intentScore: 85,
      budgetFitScore: 90,
      urgency: "high",
      propertyMatchConfidence: 88,
      riskFlags: [],
      overallScore: 87,
    },
  },
  {
    id: "2",
    prospectId: "2",
    prospectName: "Fatima Al-Zahrani",
    campaignId: "1",
    timestamp: "2024-01-15T11:15:00",
    duration: 0,
    channel: "whatsapp",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: true,
    messageCount: 24,
    qualificationScore: {
      intentScore: 92,
      budgetFitScore: 85,
      urgency: "high",
      propertyMatchConfidence: 90,
      riskFlags: ["Complex financing needs"],
      overallScore: 89,
    },
  },
  {
    id: "3",
    prospectId: "3",
    prospectName: "Sultan Al-Harbi",
    timestamp: "2024-01-15T09:00:00",
    duration: 180,
    channel: "phone",
    outcome: "connected",
    sentiment: "neutral",
    aiConfidence: "medium",
    handoffSuggested: false,
  },
  {
    id: "4",
    prospectId: "4",
    prospectName: "Mariam Al-Ghamdi",
    campaignId: "2",
    timestamp: "2024-01-15T14:30:00",
    duration: 0,
    channel: "sms",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "medium",
    messageCount: 8,
  },
  {
    id: "5",
    prospectId: "5",
    prospectName: "Abdullah Al-Mutairi",
    campaignId: "1",
    timestamp: "2024-01-15T15:00:00",
    duration: 540,
    channel: "phone",
    outcome: "qualified",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: true,
    qualificationScore: {
      intentScore: 95,
      budgetFitScore: 92,
      urgency: "high",
      propertyMatchConfidence: 94,
      riskFlags: [],
      overallScore: 94,
    },
  },
  {
    id: "6",
    prospectId: "6",
    prospectName: "Aisha Al-Harthi",
    timestamp: "2024-01-15T12:00:00",
    duration: 0,
    channel: "email",
    outcome: "opened",
    sentiment: "neutral",
    aiConfidence: "low",
  },
  {
    id: "7",
    prospectId: "7",
    prospectName: "Nasser Al-Otaibi",
    campaignId: "3",
    timestamp: "2024-01-15T16:30:00",
    duration: 0,
    channel: "whatsapp",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "high",
    messageCount: 18,
    handoffSuggested: false,
  },
  {
    id: "8",
    prospectId: "8",
    prospectName: "Sara Al-Qahtani",
    campaignId: "1",
    timestamp: "2024-01-14T10:00:00",
    duration: 380,
    channel: "phone",
    outcome: "qualified",
    sentiment: "positive",
    aiConfidence: "high",
    handoffSuggested: true,
    qualificationScore: {
      intentScore: 88,
      budgetFitScore: 95,
      urgency: "medium",
      propertyMatchConfidence: 85,
      riskFlags: ["Decision maker unclear"],
      overallScore: 89,
    },
  },
  {
    id: "9",
    prospectId: "9",
    prospectName: "Turki Al-Shamrani",
    timestamp: "2024-01-14T14:30:00",
    duration: 0,
    channel: "email",
    outcome: "clicked",
    sentiment: "neutral",
    aiConfidence: "medium",
  },
  {
    id: "10",
    prospectId: "10",
    prospectName: "Noura Al-Dosari",
    campaignId: "2",
    timestamp: "2024-01-14T11:00:00",
    duration: 0,
    channel: "whatsapp",
    outcome: "responded",
    sentiment: "positive",
    aiConfidence: "medium",
    messageCount: 12,
  },
]

// Keep mockCalls as alias for backward compatibility
export const mockCalls = mockConversations

export const mockCampaigns: Campaign[] = [
  {
    id: "1",
    name: "Riyadh Q1 Luxury Villas",
    segment: "High-Net-Worth, Riyadh",
    status: "active",
    channels: ["phone", "whatsapp", "email"],
    attempts: 2847,
    connectRate: 44,
    bookedAppointments: 127,
    createdBy: "2",
    createdAt: "2024-01-01",
    channelMetrics: {
      phone: { sent: 1200, connected: 528, rate: 44 },
      whatsapp: { sent: 1000, responded: 680, rate: 68 },
      email: { sent: 647, opened: 324, clicked: 89, rate: 14 },
    },
  },
  {
    id: "2",
    name: "Jeddah Waterfront Launch",
    segment: "Property Investors",
    status: "active",
    channels: ["whatsapp", "sms"],
    attempts: 1523,
    connectRate: 52,
    bookedAppointments: 89,
    createdBy: "2",
    createdAt: "2024-01-05",
    channelMetrics: {
      whatsapp: { sent: 1000, responded: 520, rate: 52 },
      sms: { sent: 523, responded: 183, rate: 35 },
    },
  },
  {
    id: "3",
    name: "Dammam First-Time Buyers",
    segment: "First-Time Buyers",
    status: "paused",
    channels: ["phone", "sms", "email"],
    attempts: 892,
    connectRate: 38,
    bookedAppointments: 34,
    createdBy: "8",
    createdAt: "2024-01-08",
    channelMetrics: {
      phone: { sent: 400, connected: 152, rate: 38 },
      sms: { sent: 300, responded: 87, rate: 29 },
      email: { sent: 192, opened: 96, clicked: 24, rate: 13 },
    },
  },
  {
    id: "4",
    name: "VIP Re-engagement",
    segment: "Previous Inquiries",
    status: "completed",
    channels: ["phone", "whatsapp"],
    attempts: 456,
    connectRate: 62,
    bookedAppointments: 78,
    createdBy: "2",
    createdAt: "2023-12-15",
    channelMetrics: {
      phone: { sent: 256, connected: 159, rate: 62 },
      whatsapp: { sent: 200, responded: 156, rate: 78 },
    },
  },
  {
    id: "5",
    name: "New Year Special Offers",
    segment: "All Segments",
    status: "draft",
    channels: ["email", "whatsapp", "sms"],
    attempts: 0,
    connectRate: 0,
    bookedAppointments: 0,
    createdBy: "8",
    createdAt: "2024-01-12",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    propertyId: "1",
    propertyName: "Azure Heights Villa",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-15T14:00:00",
    location: "Azure Heights Sales Center, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "2",
    prospectId: "2",
    prospectName: "Fatima Al-Zahrani",
    propertyId: "2",
    propertyName: "Pearl Tower Penthouse",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-16T10:00:00",
    location: "Pearl Tower Show Unit, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "3",
    prospectId: "5",
    prospectName: "Abdullah Al-Mutairi",
    propertyId: "5",
    propertyName: "Royal Palm Estate",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-18T16:00:00",
    location: "Royal Palm Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "4",
    prospectId: "8",
    prospectName: "Sara Al-Qahtani",
    propertyId: "5",
    propertyName: "Royal Palm Estate",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-17T11:00:00",
    location: "Royal Palm Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "5",
    prospectId: "4",
    prospectName: "Mariam Al-Ghamdi",
    propertyId: "4",
    propertyName: "Coral Bay Apartments",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2025-12-19T15:00:00",
    location: "Coral Bay Sales Office, Dammam",
    status: "scheduled",
    sourceChannel: "sms",
  },
  {
    id: "6",
    prospectId: "7",
    prospectName: "Nasser Al-Otaibi",
    propertyId: "3",
    propertyName: "Golden Oasis Residence",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2025-12-10T09:00:00",
    location: "Golden Oasis Community Center, Riyadh",
    status: "completed",
    notes: "Very interested, requested pricing details",
    sourceChannel: "whatsapp",
  },
  {
    id: "7",
    prospectId: "9",
    prospectName: "Omar Hassan",
    propertyId: "6",
    propertyName: "Sapphire Towers",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-20T13:00:00",
    location: "Sapphire Towers Sales Office, Jeddah",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "8",
    prospectId: "10",
    prospectName: "Aisha Al-Najjar",
    propertyId: "8",
    propertyName: "Marina Vista Penthouse",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2025-12-21T10:30:00",
    location: "Marina Vista Show Unit, Dammam",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "9",
    prospectId: "11",
    prospectName: "Yousef Al-Mansour",
    propertyId: "10",
    propertyName: "Crystal Palace Residence",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-22T14:30:00",
    location: "Crystal Palace, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "10",
    prospectId: "12",
    prospectName: "Huda Al-Salem",
    propertyId: "11",
    propertyName: "Horizon Heights",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2025-12-23T09:00:00",
    location: "Horizon Heights Sales Center, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "11",
    prospectId: "13",
    prospectName: "Tariq Al-Zahrani",
    propertyId: "13",
    propertyName: "Silver Dunes Estate",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-24T11:00:00",
    location: "Silver Dunes Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "12",
    prospectId: "14",
    prospectName: "Layla Al-Rashid",
    propertyId: "15",
    propertyName: "Oasis Springs Villa",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-26T15:00:00",
    location: "Oasis Springs, Riyadh",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "13",
    prospectId: "15",
    prospectName: "Hassan Al-Harbi",
    propertyId: "17",
    propertyName: "Royal Gardens Mansion",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2025-12-27T10:00:00",
    location: "Royal Gardens, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "14",
    prospectId: "16",
    prospectName: "Reem Al-Dosari",
    propertyId: "19",
    propertyName: "Green Valley Townhouse",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2025-12-28T13:30:00",
    location: "Green Valley Community, Riyadh",
    status: "scheduled",
    sourceChannel: "sms",
  },
  {
    id: "15",
    prospectId: "17",
    prospectName: "Fahad Al-Shammari",
    propertyId: "21",
    propertyName: "Paradise Hills Villa",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2025-12-29T16:00:00",
    location: "Paradise Hills, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "16",
    prospectId: "18",
    prospectName: "Mona Al-Harthi",
    propertyId: "22",
    propertyName: "Metropolitan Square",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2025-12-30T11:00:00",
    location: "Metropolitan Square, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "17",
    prospectId: "19",
    prospectName: "Saud Al-Ghamdi",
    propertyId: "24",
    propertyName: "Azure Bay Residences",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2026-01-02T10:00:00",
    location: "Azure Bay, Dammam",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "18",
    prospectId: "20",
    prospectName: "Nora Al-Mutairi",
    propertyId: "25",
    propertyName: "Skyline Tower Penthouse",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2026-01-03T14:00:00",
    location: "Skyline Tower, Riyadh",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "19",
    prospectId: "21",
    prospectName: "Ahmed Al-Jaber",
    propertyId: "7",
    propertyName: "Desert Rose Villa",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2026-01-04T09:30:00",
    location: "Desert Rose Estate, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "20",
    prospectId: "22",
    prospectName: "Khaled Al-Subai",
    propertyId: "9",
    propertyName: "Emerald Gardens Townhouse",
    assignedRepId: "11",
    assignedRepName: "Ibrahim Al-Tamimi",
    scheduledDate: "2026-01-05T15:30:00",
    location: "Emerald Gardens, Riyadh",
    status: "scheduled",
    sourceChannel: "sms",
  },
  {
    id: "21",
    prospectId: "23",
    prospectName: "Salma Al-Qahtani",
    propertyId: "12",
    propertyName: "Platinum Residence",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2026-01-06T10:30:00",
    location: "Platinum Residence, Dammam",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "22",
    prospectId: "24",
    prospectName: "Majid Al-Faisal",
    propertyId: "16",
    propertyName: "Diamond District Loft",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2026-01-07T13:00:00",
    location: "Diamond District, Dammam",
    status: "scheduled",
    sourceChannel: "email",
  },
  {
    id: "23",
    prospectId: "25",
    prospectName: "Lina Al-Harbi",
    propertyId: "18",
    propertyName: "Sunset Boulevard Penthouse",
    assignedRepId: "4",
    assignedRepName: "Layla Hassan",
    scheduledDate: "2026-01-08T16:30:00",
    location: "Sunset Boulevard, Jeddah",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
  {
    id: "24",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    propertyId: "20",
    propertyName: "Coastal Breeze Apartment",
    assignedRepId: "6",
    assignedRepName: "Noor Al-Khaled",
    scheduledDate: "2026-01-09T11:00:00",
    location: "Coastal Breeze, Dammam",
    status: "scheduled",
    sourceChannel: "phone",
  },
  {
    id: "25",
    prospectId: "3",
    prospectName: "Sarah Al-Amri",
    propertyId: "23",
    propertyName: "Heritage Palace",
    assignedRepId: "3",
    assignedRepName: "Mohammed Al-Farsi",
    scheduledDate: "2026-01-10T14:30:00",
    location: "Heritage Palace, Riyadh",
    status: "scheduled",
    sourceChannel: "whatsapp",
  },
]

export const mockIntegrations: Integration[] = [
  {
    id: "1",
    name: "Salesforce",
    type: "crm",
    status: "connected",
    lastSync: "2 minutes ago",
  },
  {
    id: "2",
    name: "Twilio Voice",
    type: "telephony",
    status: "connected",
    lastSync: "Real-time",
  },
  {
    id: "3",
    name: "WhatsApp Business API",
    type: "messaging",
    status: "connected",
    lastSync: "Real-time",
  },
  {
    id: "4",
    name: "Twilio SMS",
    type: "messaging",
    status: "connected",
    lastSync: "Real-time",
  },
  {
    id: "5",
    name: "SendGrid",
    type: "email",
    status: "connected",
    lastSync: "5 minutes ago",
  },
  {
    id: "6",
    name: "Google Calendar",
    type: "calendar",
    status: "connected",
    lastSync: "1 minute ago",
  },
  {
    id: "7",
    name: "HubSpot",
    type: "crm",
    status: "disconnected",
  },
  {
    id: "8",
    name: "Microsoft Teams",
    type: "messaging",
    status: "error",
    lastSync: "Connection failed",
  },
]

export const mockLiveConversation: LiveConversation = {
  id: "live-1",
  prospectId: "1",
  prospectName: "Khalid Abdullah",
  channel: "phone",
  status: "connected",
  duration: 127,
  sentiment: "positive",
  transcript: [
    {
      timestamp: "00:00:05",
      speaker: "agent",
      message: "Good afternoon! This is calling from First Projects Holding. Am I speaking with Khalid Abdullah?",
    },
    {
      timestamp: "00:00:12",
      speaker: "prospect",
      message: "Yes, this is Khalid speaking. How can I help you?",
    },
    {
      timestamp: "00:00:18",
      speaker: "agent",
      message:
        "Excellent! I'm reaching out regarding our exclusive luxury villa collection in Riyadh. I understand you've expressed interest in premium properties. Do you have a few moments?",
    },
    {
      timestamp: "00:00:32",
      speaker: "prospect",
      message: "Actually yes, I'm looking for something in the 3 to 5 million SAR range. What do you have available?",
    },
    {
      timestamp: "00:00:45",
      speaker: "agent",
      message:
        "Perfect! We have several stunning options. I'd particularly recommend Azure Heights Villa - a 4-bedroom with smart home integration, private pool, and 24/7 security. Would you be interested in a private viewing?",
    },
  ],
  detectedEntities: [
    { type: "budget", value: "3-5M SAR", confidence: 0.95 },
    { type: "area", value: "Riyadh", confidence: 0.92 },
    { type: "bedrooms", value: "4+", confidence: 0.78 },
    { type: "timeline", value: "3-6 months", confidence: 0.85 },
    { type: "intent", value: "High Purchase Intent", confidence: 0.89 },
  ],
  nextBestQuestion:
    "Ask about their preferred move-in timeline and whether they're considering financing options or cash purchase.",
  agentPlan: [
    {
      step: 1,
      name: "Verify Identity",
      description: "Confirm speaking with the right person",
      status: "completed",
    },
    {
      step: 2,
      name: "Build Rapport",
      description: "Establish connection and assess interest",
      status: "completed",
    },
    {
      step: 3,
      name: "Qualify Budget",
      description: "Understand financial requirements",
      status: "completed",
    },
    {
      step: 4,
      name: "Match Properties",
      description: "Present suitable options from inventory",
      status: "in_progress",
    },
    {
      step: 5,
      name: "Schedule Viewing",
      description: "Book property tour appointment",
      status: "pending",
    },
    {
      step: 6,
      name: "Log & Handoff",
      description: "Update CRM and prepare handoff package",
      status: "pending",
    },
  ],
}

// Keep mockLiveCall as alias
export const mockLiveCall = mockLiveConversation

export const mockLiveWhatsApp: LiveConversation = {
  id: "live-2",
  prospectId: "2",
  prospectName: "Fatima Al-Zahrani",
  channel: "whatsapp",
  status: "connected",
  duration: 0,
  sentiment: "positive",
  transcript: [
    {
      timestamp: "14:30",
      speaker: "agent",
      message:
        "Hello Fatima! This is the AI assistant from First Projects Holding. Thank you for your interest in our luxury properties in Jeddah. How may I assist you today?",
    },
    {
      timestamp: "14:32",
      speaker: "prospect",
      message: "Hi! I saw your Pearl Tower listing. Can you tell me more about the penthouse units?",
    },
    {
      timestamp: "14:32",
      speaker: "agent",
      message:
        "Of course! The Pearl Tower Penthouse is our flagship offering with stunning Red Sea views. It features 3 bedrooms, a private rooftop terrace, and 24/7 concierge service. The price range is 6.8M - 7.5M SAR. Would you like to see the floor plans?",
    },
    {
      timestamp: "14:35",
      speaker: "prospect",
      message: "Yes please! Also, do you have any payment plans?",
    },
  ],
  detectedEntities: [
    { type: "budget", value: "6-8M SAR", confidence: 0.88 },
    { type: "area", value: "Jeddah", confidence: 0.98 },
    { type: "intent", value: "High Purchase Intent", confidence: 0.91 },
  ],
  nextBestQuestion:
    "Share the floor plans and inquire about their financing preference - developer payment plan vs bank mortgage.",
  agentPlan: [
    { step: 1, name: "Greet & Engage", description: "Welcome and acknowledge interest", status: "completed" },
    { step: 2, name: "Present Property", description: "Share details about Pearl Tower", status: "completed" },
    { step: 3, name: "Share Media", description: "Send floor plans and virtual tour", status: "in_progress" },
    { step: 4, name: "Discuss Financing", description: "Explain payment options", status: "pending" },
    { step: 5, name: "Schedule Viewing", description: "Book site visit", status: "pending" },
  ],
}

export const mockCampaignRun: CampaignRun = {
  id: "run-1",
  campaignId: "1",
  campaignName: "Riyadh Q1 Luxury Villas",
  status: "running",
  startedAt: "2024-01-15T09:00:00",
  queue: [
    {
      id: "q1",
      prospectId: "1",
      prospectName: "Khalid Abdullah",
      phone: "+966 50 123 4567",
      channel: "phone",
      status: "connected",
      attempts: 1,
    },
    {
      id: "q2",
      prospectId: "2",
      prospectName: "Fatima Al-Zahrani",
      phone: "+966 55 234 5678",
      whatsapp: "+966 55 234 5678",
      channel: "whatsapp",
      status: "responded",
      attempts: 1,
    },
    {
      id: "q3",
      prospectId: "3",
      prospectName: "Sultan Al-Harbi",
      phone: "+966 50 345 6789",
      channel: "phone",
      status: "queued",
      attempts: 0,
    },
    {
      id: "q4",
      prospectId: "4",
      prospectName: "Mariam Al-Ghamdi",
      phone: "+966 55 456 7890",
      email: "mariam@example.com",
      channel: "email",
      status: "delivered",
      attempts: 1,
    },
    {
      id: "q5",
      prospectId: "5",
      prospectName: "Abdullah Al-Mutairi",
      phone: "+966 50 567 8901",
      channel: "phone",
      status: "completed",
      attempts: 1,
    },
  ],
  currentConversation: mockLiveConversation,
  metrics: {
    totalLeads: 150,
    contacted: 87,
    connected: 42,
    voicemails: 15,
    noAnswers: 30,
    booked: 12,
    connectRate: 48,
    byChannel: {
      phone: { contacted: 45, connected: 22 },
      whatsapp: { sent: 30, responded: 18 },
      email: { sent: 12, opened: 8 },
    },
  },
}

export const mockHandoffPackages: HandoffPackage[] = [
  {
    id: "ho-1",
    conversationId: "2",
    prospectId: "2",
    prospectName: "Fatima Al-Zahrani",
    prospectPhone: "+966 55 234 5678",
    prospectEmail: "fatima@example.com",
    prospectWhatsapp: "+966 55 234 5678",
    timestamp: "2024-01-15T11:45:00",
    priority: "high",
    sourceChannel: "whatsapp",
    suggestedFollowUpChannel: "phone",
    reason: "Complex financing questions requiring human expertise",
    summary:
      "High-value prospect interested in Pearl Tower Penthouse. Has specific questions about developer payment plans and bank financing options. Ready to proceed but needs detailed financial consultation.",
    detectedNeeds: [
      "Payment plan details",
      "Bank financing options",
      "Legal documentation",
      "Move-in timeline flexibility",
    ],
    suggestedProperties: ["Pearl Tower Penthouse", "Azure Heights Villa"],
    qualificationScore: {
      intentScore: 92,
      budgetFitScore: 85,
      urgency: "high",
      propertyMatchConfidence: 90,
      riskFlags: ["Complex financing needs"],
      overallScore: 89,
    },
    conversationContext:
      "24-message WhatsApp conversation. Prospect showed strong interest in Pearl Tower, requested floor plans and payment details. Questions became technical regarding mortgage vs developer financing.",
    nextSteps: [
      "Call to discuss financing options",
      "Prepare payment plan comparison",
      "Schedule property viewing",
      "Connect with finance team",
    ],
    status: "pending",
  },
  {
    id: "ho-2",
    conversationId: "5",
    prospectId: "5",
    prospectName: "Abdullah Al-Mutairi",
    prospectPhone: "+966 50 567 8901",
    prospectEmail: "abdullah.m@example.com",
    prospectWhatsapp: "+966 50 567 8901",
    timestamp: "2024-01-15T15:30:00",
    priority: "high",
    sourceChannel: "phone",
    suggestedFollowUpChannel: "phone",
    reason: "VIP prospect requesting exclusive properties",
    summary:
      "Ultra-high-net-worth individual interested in Royal Palm Estate. Looking for immediate purchase with cash. Requesting private viewing with senior management.",
    detectedNeeds: ["Exclusive property access", "VIP treatment", "Senior management meeting", "Quick closing process"],
    suggestedProperties: ["Royal Palm Estate"],
    qualificationScore: {
      intentScore: 95,
      budgetFitScore: 92,
      urgency: "high",
      propertyMatchConfidence: 94,
      riskFlags: [],
      overallScore: 94,
    },
    conversationContext:
      "9-minute call. Prospect directly asked for the most exclusive property available. Mentioned cash purchase and requested meeting with company leadership.",
    nextSteps: [
      "Arrange CEO introduction",
      "Schedule private estate viewing",
      "Prepare bespoke presentation",
      "Fast-track documentation",
    ],
    status: "claimed",
    claimedBy: "Mohammed Al-Farsi",
    claimedAt: "2024-01-15T15:45:00",
  },
  {
    id: "ho-3",
    conversationId: "8",
    prospectId: "8",
    prospectName: "Sara Al-Qahtani",
    prospectPhone: "+966 55 890 1234",
    prospectEmail: "sara.q@example.com",
    prospectWhatsapp: "+966 55 890 1234",
    timestamp: "2024-01-14T10:30:00",
    priority: "medium",
    sourceChannel: "phone",
    suggestedFollowUpChannel: "whatsapp",
    reason: "Family decision - needs spouse involvement",
    summary:
      "Interested in Royal Palm Estate but needs to consult with spouse. Requested materials to share and follow-up in a week.",
    detectedNeeds: [
      "Family consultation time",
      "Shareable materials",
      "Flexible viewing schedule",
      "Child-friendly features",
    ],
    suggestedProperties: ["Royal Palm Estate", "Golden Oasis Residence"],
    qualificationScore: {
      intentScore: 88,
      budgetFitScore: 95,
      urgency: "medium",
      propertyMatchConfidence: 85,
      riskFlags: ["Decision maker unclear"],
      overallScore: 89,
    },
    conversationContext:
      "6-minute call. Strong interest but explicitly mentioned needing spouse approval. Asked about family amenities and schools nearby.",
    nextSteps: [
      "Send digital brochure via WhatsApp",
      "Schedule follow-up in 5 days",
      "Include family amenities info",
      "Offer family viewing",
    ],
    status: "pending",
  },
  {
    id: "ho-4",
    conversationId: "7",
    prospectId: "7",
    prospectName: "Nasser Al-Otaibi",
    prospectPhone: "+966 50 789 0123",
    prospectEmail: "nasser@example.com",
    prospectWhatsapp: "+966 50 789 0123",
    timestamp: "2024-01-15T17:00:00",
    priority: "medium",
    sourceChannel: "whatsapp",
    suggestedFollowUpChannel: "whatsapp",
    reason: "Investment property inquiry - needs ROI discussion",
    summary:
      "Investor interested in rental yield potential. Looking at multiple units for investment portfolio. Needs detailed ROI analysis.",
    detectedNeeds: ["ROI projections", "Rental yield data", "Multiple unit pricing", "Investment portfolio advice"],
    suggestedProperties: ["Golden Oasis Residence", "Coral Bay Apartments"],
    qualificationScore: {
      intentScore: 82,
      budgetFitScore: 88,
      urgency: "medium",
      propertyMatchConfidence: 80,
      riskFlags: ["Investment buyer - longer decision cycle"],
      overallScore: 83,
    },
    conversationContext:
      "18-message WhatsApp thread. Prospect is building investment portfolio. Asked detailed questions about rental market and expected returns.",
    nextSteps: [
      "Prepare investment analysis",
      "Share rental yield data",
      "Offer bulk purchase incentives",
      "Connect with investment advisor",
    ],
    status: "pending",
  },
  {
    id: "ho-5",
    conversationId: "1",
    prospectId: "1",
    prospectName: "Khalid Abdullah",
    prospectPhone: "+966 50 123 4567",
    prospectEmail: "khalid@example.com",
    prospectWhatsapp: "+966 50 123 4567",
    timestamp: "2024-01-15T11:00:00",
    priority: "high",
    sourceChannel: "phone",
    suggestedFollowUpChannel: "phone",
    reason: "Ready to book viewing - high intent",
    summary:
      "Qualified lead ready for property viewing. Showed strong interest in Azure Heights Villa. Has budget confirmed and timeline of 3-6 months.",
    detectedNeeds: ["Property viewing", "Smart home demonstration", "Pool and garden tour", "Security briefing"],
    suggestedProperties: ["Azure Heights Villa", "Golden Oasis Residence"],
    qualificationScore: {
      intentScore: 85,
      budgetFitScore: 90,
      urgency: "high",
      propertyMatchConfidence: 88,
      riskFlags: [],
      overallScore: 87,
    },
    conversationContext:
      "7-minute call. Very engaged, asked specific questions about smart home features and security. Ready to schedule viewing.",
    nextSteps: [
      "Confirm viewing appointment",
      "Prepare property presentation",
      "Arrange smart home demo",
      "Send location and parking details",
    ],
    status: "completed",
    claimedBy: "Mohammed Al-Farsi",
    claimedAt: "2024-01-15T11:15:00",
  },
]

export const mockRoutingRules: RoutingRule[] = [
  {
    id: "1",
    name: "VIP Riyadh Routing",
    conditions: [
      { field: "city", operator: "equals", value: "Riyadh" },
      { field: "budget", operator: "greaterThan", value: "10000000" },
    ],
    assignTo: "3",
    priority: 1,
    enabled: true,
  },
  {
    id: "2",
    name: "Jeddah Leads",
    conditions: [{ field: "city", operator: "equals", value: "Jeddah" }],
    assignTo: "4",
    priority: 2,
    enabled: true,
  },
  {
    id: "3",
    name: "WhatsApp Preference",
    conditions: [{ field: "channel", operator: "equals", value: "whatsapp" }],
    assignTo: "auto",
    priority: 3,
    enabled: true,
  },
]
